"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { useAttendance } from "@/components/attendance-provider";
import { Avatar, EmptyState, EmployeeStatusBadge, PageHeading, ProgressBar, StatusBadge } from "@/components/ui";
import { defaultBalance } from "@/lib/leave";
import { formatShortDate, percentageFor } from "@/lib/attendance";
import { formatMinutes, isScheduledDate, shiftArrangement, shiftDisplayName as shiftNameWithArrangement } from "@/lib/scheduling";

const shiftDisplayName = (shift: Parameters<typeof shiftNameWithArrangement>[0]) => shift.name;

export default function EmployeeDetailsPage() {
  const { id } = useParams<{ id: string }>(); const { canManageEmployees, canManageShifts } = useAuth(); const { employees, records, leaveRequests, balances, shifts, assignments, setEmployeeShift, holidays, workingDays } = useAttendance();
  const employee = employees.find((item) => item.id === decodeURIComponent(id)); if (!employee) return <EmptyState title="Employee not found" description="This profile is unavailable or has been deleted." />;
  const own = records.filter((record) => record.employeeId === employee.id).sort((a, b) => b.date.localeCompare(a.date)); const leaves = leaveRequests.filter((request) => request.employeeId === employee.id).sort((a, b) => b.requestDate.localeCompare(a.requestDate)); const count = (status: string) => own.filter((record) => record.status === status).length; const shift = shifts.find((item) => item.id === assignments[employee.id]); const pct = percentageFor(records, employee.id, undefined, (date) => isScheduledDate(date, workingDays, holidays, shift)); const balance = balances[employee.id] || defaultBalance(); const worked = own.reduce((total, record) => total + (record.workedMinutes || 0), 0); const overtime = own.reduce((total, record) => total + (record.overtimeMinutes || 0), 0);
  return <div className="space-y-6">
    <PageHeading eyebrow="People / Employees" title={employee.name} description={`${employee.role} · ${employee.department}`} action={canManageEmployees ? <Link className="btn-primary" href={`/employees/${encodeURIComponent(employee.id)}/edit`}>Edit Employee</Link> : undefined} />
    <section className="profile-hero"><div className="flex min-w-0 items-center gap-4"><Avatar initials={employee.initials} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-bold">{employee.name}</h2><EmployeeStatusBadge status={employee.status} /></div><p className="mt-1 text-sm text-slate-500">{employee.role} · {employee.department}</p><p className="mt-1 text-xs text-slate-400">{employee.id} · {employee.email}</p></div></div><div className="profile-facts"><div><span>Shift</span><b>{shift ? shiftDisplayName(shift) : "Unassigned"}</b></div><div><span>Arrangement</span><b>{shiftArrangement(shift)}</b></div><div><span>Location</span><b>{employee.location}</b></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_1.5fr]"><article className="panel p-5"><h2 className="section-title">Employment overview</h2><p className="section-copy">Contact and reporting information</p><dl className="details-grid"><div><dt>Employee ID</dt><dd>{employee.id}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${employee.email}`}>{employee.email}</a></dd></div><div><dt>Phone</dt><dd>{employee.phone}</dd></div><div><dt>Joining date</dt><dd>{formatShortDate(employee.joiningDate)}</dd></div><div><dt>Manager</dt><dd>{employee.manager}</dd></div><div><dt>Department</dt><dd>{employee.department}</dd></div></dl>{canManageShifts ? <label className="form-field mt-5"><span>Assigned shift</span><select value={assignments[employee.id] || ""} onChange={(event) => setEmployeeShift(employee.id, event.target.value)}><option value="">Unassigned</option>{shifts.filter((item) => item.status === "Active" || item.id === assignments[employee.id]).map((item) => <option key={item.id} value={item.id}>{shiftDisplayName(item)} · {shiftArrangement(item)} ({item.startTime}–{item.endTime})</option>)}</select></label> : <div className="mt-5"><p className="text-xs font-medium text-slate-500">Assigned shift</p><p className="mt-1 text-sm font-semibold text-slate-800">{shift ? `${shiftDisplayName(shift)} (${shift.startTime}–${shift.endTime})` : "Unassigned"}</p></div>}</article>
      <article className="panel p-5"><h2 className="section-title">Attendance summary</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Present", "present"], ["Absent", "absent"], ["Late", "late"], ["Leave", "leave"], ["Half Day", "half-day"], ["Work From Home", "work-from-home"]].map(([label, status]) => <div className="metric" key={status}><span>{label}</span><b>{count(status)}</b></div>)}</div><div className="mt-3 grid grid-cols-2 gap-3"><div className="metric"><span>Total worked</span><b className="text-base">{formatMinutes(worked)}</b></div><div className="metric"><span>Total overtime</span><b className="text-base">{formatMinutes(overtime)}</b></div></div><div className="mt-5 flex items-center gap-4"><div className="flex-1"><ProgressBar value={pct} /></div><b>{pct}%</b></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="balance-card"><span>Annual leave</span><b>{Math.max(0, balance.annualAllowance - balance.annualUsed)} remaining</b><small>{balance.annualUsed} of {balance.annualAllowance} used</small></div><div className="balance-card"><span>Sick leave</span><b>{Math.max(0, balance.sickAllowance - balance.sickUsed)} remaining</b><small>{balance.sickUsed} of {balance.sickAllowance} used</small></div></div></article></section>
    <section className="grid gap-6 xl:grid-cols-2"><article className="panel overflow-hidden"><div className="panel-heading"><h2 className="section-title">Recent attendance</h2></div>{own.length ? <div className="divide-y divide-slate-100">{own.slice(0, 6).map((record) => <div className="flex flex-col gap-2 px-5 py-3 sm:flex-row sm:items-center sm:justify-between" key={record.date}><div><span className="text-sm font-medium">{formatShortDate(record.date)}</span><p className="text-xs text-slate-500">{record.checkIn || "No check-in"} – {record.checkOut || "No check-out"}{record.workedMinutes != null ? ` · ${formatMinutes(record.workedMinutes)}` : ""}</p></div><div className="flex items-center gap-2">{record.overtimeMinutes ? <span className="text-xs font-medium text-violet-600">+{formatMinutes(record.overtimeMinutes)} OT</span> : null}{record.earlyDepartureMinutes ? <span className="text-xs font-medium text-amber-700">{record.earlyDepartureMinutes}m early</span> : null}<StatusBadge status={record.status} /></div></div>)}</div> : <EmptyState title="No attendance history" description="Attendance entries will appear here once marked." />}</article><article className="panel overflow-hidden"><div className="panel-heading"><h2 className="section-title">Leave history</h2></div>{leaves.length ? <div className="table-wrap"><table className="min-w-[560px]"><thead><tr><th>Type</th><th>Dates</th><th>Days</th><th>Status</th></tr></thead><tbody>{leaves.map((leave) => <tr key={leave.id}><td>{leave.type}</td><td>{formatShortDate(leave.startDate)} – {formatShortDate(leave.endDate)}</td><td>{leave.days}</td><td><span className={`leave-badge leave-${leave.status.toLowerCase()}`}>{leave.status}</span></td></tr>)}</tbody></table></div> : <EmptyState title="No leave history" description="Leave requests for this employee will appear here." />}</article></section>
  </div>;
}
