"use client";
import { FormEvent, useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { useOperations } from "@/components/operations-provider";
import { Avatar, EmptyState, PageHeading } from "@/components/ui";
import { daysInclusive, defaultBalance, LeaveStatus, leaveTypes } from "@/lib/leave";
import { formatShortDate } from "@/lib/attendance";

export default function LeavePage() {
  const { currentUser, role, canManageLeave } = useAuth(); const { settings, addAudit } = useOperations(); const { activeEmployees, employees, leaveRequests, balances, addLeaveRequest, updateLeaveStatus } = useAttendance(); const [open, setOpen] = useState(false); const [employeeId, setEmployee] = useState(currentUser?.employeeId || ""); const [type, setType] = useState<(typeof leaveTypes)[number]>("Annual Leave"); const [startDate, setStart] = useState(""); const [endDate, setEnd] = useState(""); const [reason, setReason] = useState(""); const own = role === "employee"; const days = daysInclusive(startDate, endDate);
  function submit(event: FormEvent) { event.preventDefault(); const target = own ? currentUser?.employeeId || "" : employeeId; if (!target || !startDate || !endDate || endDate < startDate || !reason.trim()) return; addLeaveRequest({ employeeId: target, type, startDate, endDate, days, reason: reason.trim() }); addAudit("submitted", "leave request", target, `${target} submitted ${type}.`); setOpen(false); setStart(""); setEnd(""); setReason(""); }
  function review(id: string, decision: "approve" | "reject") { const request = leaveRequests.find((item) => item.id === id); if (!request || !canManageLeave || request.employeeId === currentUser?.employeeId) return; let next: LeaveStatus = "Rejected"; if (decision === "approve") next = role === "manager" && settings.hrFinalApprovalRequired ? "Pending HR" : "Approved"; updateLeaveStatus(id, next); addAudit(decision === "approve" ? "approved" : "rejected", "leave request", id, `${next}: ${request.employeeId} leave request.`); }
  return <div className="space-y-6"><PageHeading title={own ? "My leave" : role === "manager" ? "Team leave requests" : "Leave management"} description="Review requests, approval progress, and available balances." action={<button className="btn-primary" onClick={() => setOpen(!open)}>{open ? "Close form" : "New leave request"}</button>} />
    {open && <form className="panel overflow-hidden" onSubmit={submit}><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3">{!own && <label className="form-field"><span>Employee</span><select required value={employeeId} onChange={(event) => setEmployee(event.target.value)}><option value="">Select authorized employee</option>{activeEmployees.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="form-field"><span>Leave type</span><select value={type} onChange={(event) => setType(event.target.value as typeof type)}>{leaveTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="form-field"><span>Start date</span><input required type="date" value={startDate} onChange={(event) => setStart(event.target.value)} /></label><label className="form-field"><span>End date</span><input required type="date" min={startDate} value={endDate} onChange={(event) => setEnd(event.target.value)} /></label><label className="form-field sm:col-span-2"><span>Reason</span><textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label></div><div className="flex items-center justify-between border-t border-slate-100 bg-slate-50/60 p-5"><span className="text-sm font-medium">{days} {days === 1 ? "day" : "days"}</span><button className="btn-primary">Submit request</button></div></form>}
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_19rem]"><article className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Leave requests</h2><p className="section-copy">{leaveRequests.length} requests in your authorized scope</p></div></div>{leaveRequests.length ? <div className="divide-y divide-slate-100">{leaveRequests.map((request) => { const employee = employees.find((item) => item.id === request.employeeId); const managerStep = role === "manager" && (request.status === "Pending Manager" || request.status === "Pending"); const finalStep = (role === "admin" || role === "hr") && (request.status === "Pending HR" || (!settings.managerApprovalRequired && ["Pending Manager", "Pending"].includes(request.status))); const mayReview = request.employeeId !== currentUser?.employeeId && (managerStep || finalStep); return <div className="leave-request-row" key={request.id}><div className="flex min-w-0 items-center gap-3"><Avatar initials={employee?.initials || request.employeeId.slice(-2)} /><div className="min-w-0"><b className="block truncate text-sm text-slate-900">{employee?.name || request.employeeId}</b><span className="text-xs text-slate-500">{request.type}</span></div></div><div><span className="leave-row-label">Dates</span><b>{formatShortDate(request.startDate)} – {formatShortDate(request.endDate)}</b><small>{request.days} {request.days === 1 ? "day" : "days"}</small></div><div><span className="leave-row-label">Status</span><span className={`leave-badge leave-${request.status.toLowerCase().replaceAll(" ", "-")}`}>{request.status}</span></div><p className="min-w-0 text-xs text-slate-500">{request.reason}</p><div>{mayReview ? <div className="flex flex-wrap gap-2"><button className="table-action text-emerald-700" onClick={() => review(request.id, "approve")}>{managerStep && settings.hrFinalApprovalRequired ? "Manager approve" : "Final approve"}</button><button className="table-action text-rose-600" onClick={() => review(request.id, "reject")}>Reject</button></div> : <span className="text-xs text-slate-400">No action required</span>}</div></div>; })}</div> : <EmptyState title="No leave requests" description="New requests will appear here." />}</article>
      <aside className="panel h-fit overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Leave balances</h2><p className="section-copy">Available days</p></div></div><div className="max-h-[34rem] divide-y divide-slate-100 overflow-y-auto">{activeEmployees.map((employee) => { const balance = balances[employee.id] || defaultBalance(); return <div className="p-4" key={employee.id}><p className="truncate text-sm font-semibold">{employee.name}</p><div className="mt-2 grid grid-cols-2 gap-2"><div className="leave-balance"><span>Annual</span><b>{Math.max(0, balance.annualAllowance - balance.annualUsed)}</b></div><div className="leave-balance"><span>Sick</span><b>{Math.max(0, balance.sickAllowance - balance.sickUsed)}</b></div></div></div>; })}</div></aside></section>
  </div>;
}
