"use client";
import { FormEvent, useMemo, useState } from "react";
import { useAttendance } from "@/components/attendance-provider"; import { EmptyState, PageHeading } from "@/components/ui"; import { daysInclusive, defaultBalance, LeaveStatus, leaveTypes } from "@/lib/leave"; import { formatShortDate } from "@/lib/attendance";
export default function LeavePage() {
  const { activeEmployees, employees, leaveRequests, balances, addLeaveRequest, updateLeaveStatus } = useAttendance(); const [showForm, setShowForm] = useState(false); const [employeeId, setEmployeeId] = useState(""); const [type, setType] = useState<(typeof leaveTypes)[number]>("Annual Leave"); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [reason, setReason] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({}); const [filter, setFilter] = useState<LeaveStatus | "">(""); const days = daysInclusive(startDate, endDate);
  const filtered = useMemo(() => leaveRequests.filter((request) => !filter || request.status === filter).sort((a, b) => b.requestDate.localeCompare(a.requestDate)), [leaveRequests, filter]);
  function submit(event: FormEvent) { event.preventDefault(); const next: Record<string, string> = {}; if (!activeEmployees.some((employee) => employee.id === employeeId)) next.employeeId = "Select a valid active employee."; if (!startDate) next.startDate = "Start date is required."; if (!endDate) next.endDate = "End date is required."; else if (startDate && endDate < startDate) next.endDate = "End date cannot be before start date."; if (!reason.trim()) next.reason = "Please provide a reason."; setErrors(next); if (Object.keys(next).length) return; addLeaveRequest({ employeeId, type, startDate, endDate, days, reason: reason.trim() }); setEmployeeId(""); setStartDate(""); setEndDate(""); setReason(""); setShowForm(false); }
  const changeStatus = (id: string, status: LeaveStatus) => { if (window.confirm(`${status} this leave request?`)) updateLeaveStatus(id, status); };
  return <div className="space-y-6"><PageHeading title="Leave requests" description="Create, review, and manage employee leave in one place." action={<button className="btn-primary" onClick={() => setShowForm((value) => !value)}>{showForm ? "Close form" : "New leave request"}</button>} />
    {showForm && <form className="panel" onSubmit={submit} noValidate><div className="panel-heading"><div><h2 className="section-title">Create leave request</h2><p className="section-copy">The duration is calculated automatically.</p></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3"><label className="form-field"><span>Employee *</span><select value={employeeId} aria-invalid={!!errors.employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">Select employee</option>{activeEmployees.map((employee) => <option value={employee.id} key={employee.id}>{employee.name} ({employee.id})</option>)}</select>{errors.employeeId && <small role="alert">{errors.employeeId}</small>}</label><label className="form-field"><span>Leave type *</span><select value={type} onChange={(event) => setType(event.target.value as typeof type)}>{leaveTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="form-field"><span>Start date *</span><input type="date" value={startDate} aria-invalid={!!errors.startDate} onChange={(event) => setStartDate(event.target.value)} />{errors.startDate && <small role="alert">{errors.startDate}</small>}</label><label className="form-field"><span>End date *</span><input type="date" value={endDate} min={startDate} aria-invalid={!!errors.endDate} onChange={(event) => setEndDate(event.target.value)} />{errors.endDate && <small role="alert">{errors.endDate}</small>}</label><label className="form-field lg:col-span-2"><span>Reason *</span><textarea rows={3} value={reason} aria-invalid={!!errors.reason} onChange={(event) => setReason(event.target.value)} />{errors.reason && <small role="alert">{errors.reason}</small>}</label></div><div className="flex items-center justify-between border-t border-slate-100 p-5"><p className="text-sm text-slate-500">Duration: <b className="text-slate-900">{days} {days === 1 ? "day" : "days"}</b></p><button className="btn-primary" type="submit">Submit request</button></div></form>}
    <section className="grid gap-6 xl:grid-cols-[1.7fr_1fr]"><div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Request history</h2><p className="section-copy">{filtered.length} requests</p></div><label className="filter-field"><span className="sr-only">Filter leave status</span><select value={filter} onChange={(event) => setFilter(event.target.value as LeaveStatus | "")}><option value="">All statuses</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></label></div>{filtered.length === 0 ? <EmptyState title={leaveRequests.length ? "No filtered leave requests" : "No leave requests"} description={leaveRequests.length ? "Choose another status filter." : "Create the first leave request to begin."} /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Type / reason</th><th>Dates</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((request) => { const employee = employees.find((item) => item.id === request.employeeId); return <tr key={request.id}><td><p className="font-semibold text-slate-900">{employee?.name || request.employeeId}</p><p className="text-xs">Requested {formatShortDate(request.requestDate)}</p></td><td><p className="font-medium">{request.type}</p><p className="max-w-52 truncate text-xs">{request.reason}</p></td><td className="whitespace-nowrap">{formatShortDate(request.startDate)} – {formatShortDate(request.endDate)}<p className="text-xs">{request.days} days</p></td><td><span className={`leave-badge leave-${request.status.toLowerCase()}`}>{request.status}</span></td><td>{request.status === "Pending" ? <div className="flex gap-2"><button className="table-action text-emerald-700" onClick={() => changeStatus(request.id, "Approved")}>Approve</button><button className="table-action text-rose-600" onClick={() => changeStatus(request.id, "Rejected")}>Reject</button></div> : <span className="text-xs text-slate-400">Completed</span>}</td></tr>; })}</tbody></table></div>}</div>
      <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Leave balances</h2><p className="section-copy">Allowance remaining</p></div></div><div className="divide-y divide-slate-100">{activeEmployees.map((employee) => { const balance = balances[employee.id] || defaultBalance(); return <div key={employee.id} className="px-5 py-3"><p className="text-sm font-semibold">{employee.name}</p><div className="mt-1 flex justify-between text-xs text-slate-500"><span>Annual: <b>{Math.max(0, balance.annualAllowance - balance.annualUsed)}</b></span><span>Sick: <b>{Math.max(0, balance.sickAllowance - balance.sickUsed)}</b></span></div></div>; })}</div></div></section>
  </div>;
}
