"use client";
import { useMemo, useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { PageHeading as BasePageHeading } from "@/components/ui";
import { getMonthKey } from "@/lib/attendance";
const monthName = (key: string) => new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${key}-01T00:00:00Z`));
const PageHeading = (props: Parameters<typeof BasePageHeading>[0]) => { const { role } = useAuth(); return <BasePageHeading {...props} title={role === "employee" ? "My Calendar" : props.title} description={role === "employee" ? "View your holidays, approved leave, and attendance exceptions." : props.description} />; };

export default function CalendarPage() {
  const { holidays, leaveRequests, employees, records } = useAttendance(); const [month, setMonth] = useState(getMonthKey()); const cells = useMemo(() => { const [year, index] = month.split("-").map(Number); const first = new Date(Date.UTC(year, index - 1, 1)); const days = new Date(Date.UTC(year, index, 0)).getUTCDate(); return [...Array(first.getUTCDay()).fill(null), ...Array.from({ length: days }, (_, i) => `${month}-${String(i + 1).padStart(2, "0")}`)]; }, [month]); const move = (offset: number) => { const date = new Date(`${month}-01T00:00:00Z`); date.setUTCMonth(date.getUTCMonth() + offset); setMonth(date.toISOString().slice(0, 7)); };
  return <div className="space-y-6"><PageHeading title="Workforce Calendar" description="A role-scoped monthly view of holidays, approved leave, and attendance exceptions." action={<div className="flex items-center gap-2"><button className="btn-secondary" onClick={() => move(-1)} aria-label="Previous month">←</button><label className="date-field"><span className="sr-only">Calendar month</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><button className="btn-secondary" onClick={() => move(1)} aria-label="Next month">→</button></div>} /><section className="panel overflow-hidden"><div className="panel-heading"><h2 className="section-title">{monthName(month)}</h2><div className="flex flex-wrap gap-3 text-xs"><span className="text-blue-700">● Holiday</span><span className="text-emerald-700">● Approved leave</span><span className="text-amber-700">● Attendance exception</span></div></div><div className="overflow-x-auto"><div className="min-w-[700px]"><div className="grid grid-cols-7 border-b border-slate-200 bg-slate-50">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <div className="p-2 text-center text-[11px] font-bold uppercase text-slate-500" key={day}>{day}</div>)}</div><div className="grid grid-cols-7">{cells.map((date, index) => { if (!date) return <div className="min-h-24 border-b border-r border-slate-100 bg-slate-50/40" key={`blank-${index}`} />; const holiday = holidays.find((item) => item.date === date); const leaves = leaveRequests.filter((item) => item.status === "Approved" && item.startDate <= date && item.endDate >= date); const exceptions = records.filter((item) => item.date === date && (item.status === "late" || item.status === "absent")); return <div className="min-h-24 overflow-hidden border-b border-r border-slate-100 p-2" key={date}><b className="text-xs">{Number(date.slice(-2))}</b><div className="mt-1 space-y-1">{holiday && <p className="truncate rounded bg-blue-50 px-1.5 py-1 text-[10px] font-semibold text-blue-700" title={holiday.name}>{holiday.name}</p>}{leaves.slice(0, 2).map((leave) => <p className="truncate rounded bg-emerald-50 px-1.5 py-1 text-[10px] text-emerald-700" key={leave.id}>{employees.find((item) => item.id === leave.employeeId)?.name || leave.employeeId} · Leave</p>)}{exceptions.length > 0 && <p className="rounded bg-amber-50 px-1.5 py-1 text-[10px] text-amber-700">{exceptions.length} exception{exceptions.length === 1 ? "" : "s"}</p>}</div></div>; })}</div></div></div></section></div>;
}
