"use client";
import Link from "next/link";
import { useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { Icon } from "@/components/icons";
import { useOperations } from "@/components/operations-provider";
import { SectionTabs } from "@/components/section-tabs";
import { Avatar, StatCard, StatusBadge } from "@/components/ui";
import { useWorkforce } from "@/components/workforce-provider";
import { breakMinutesFor, getToday, isAttendedStatus } from "@/lib/attendance";
import { formatMinutes, isScheduledDate, timeToMinutes } from "@/lib/scheduling";
import { resolvedSchedule } from "@/lib/workforce";

export default function WorkforcePage() {
  const auth = useAuth(); const data = useAttendance(); const { schedules } = useWorkforce(); const { corrections } = useOperations(); const [search, setSearch] = useState(""); const [state, setState] = useState(""); const today = getToday(); const now = new Date().toTimeString().slice(0, 5);
  const scoped = data.activeEmployees.filter((employee) => auth.role !== "manager" || auth.currentUser?.teamIds.includes(employee.id));
  const allRows = scoped.map((employee) => { const record = data.records.find((item) => item.employeeId === employee.id && item.date === today); const shift = resolvedSchedule(schedules, employee.id, today, data.assignments[employee.id], data.shifts); const leave = data.leaveRequests.some((item) => item.employeeId === employee.id && item.status === "Approved" && item.startDate <= today && item.endDate >= today); const activeBreak = record?.breaks?.some((item) => !item.end); const missing = !!record?.checkIn && !record.checkOut && !!shift && timeToMinutes(now) > timeToMinutes(shift.endTime); const breakMinutes = breakMinutesFor(record, now); const workedMinutes = record?.workedMinutes ?? (record?.checkIn ? Math.max(0, timeToMinutes(now) - timeToMinutes(record.checkIn) - breakMinutes) : 0); const currentState = leave ? "On Leave" : activeBreak ? "On Break" : record?.checkOut ? "Checked Out" : missing ? "Missing Checkout" : record?.checkIn ? (record.status === "late" ? "Late" : "Working") : shift && isScheduledDate(today, data.workingDays, data.holidays, data.shifts.find((item) => item.id === shift.shiftId)) ? "Not Checked In" : "Not Scheduled"; return { employee, record, shift, currentState, activeBreak, breakMinutes, workedMinutes }; });
  const rows = allRows.filter((row) => (!search || `${row.employee.name} ${row.employee.id}`.toLowerCase().includes(search.toLowerCase())) && (!state || row.currentState === state)); const count = (value: string) => allRows.filter((row) => row.currentState === value).length; const working = allRows.filter((row) => row.record?.checkIn && !row.record.checkOut).length; const pendingCorrections = corrections.filter((item) => item.status === "Pending" && scoped.some((employee) => employee.id === item.employeeId)).length; const pendingLeave = data.leaveRequests.filter((item) => item.status.startsWith("Pending") && scoped.some((employee) => employee.id === item.employeeId)).length;
  const trend = Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() - (6 - offset)); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; const records = data.records.filter((item) => item.date === key && scoped.some((employee) => employee.id === item.employeeId)); return { day: date.toLocaleDateString("en-US", { weekday: "short" }), date: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }), value: records.filter((item) => isAttendedStatus(item.status)).length }; }); const max = Math.max(1, ...trend.map((item) => item.value)); const points = trend.map((item, index) => `${45 + index * 86},${172 - item.value / max * 125}`).join(" "); const firstShift = allRows.find((row) => row.shift)?.shift;
  return <div className="space-y-4"><div className="flex justify-end gap-3"><Link className="btn-secondary" href="/corrections">Review corrections</Link>{auth.role !== "manager" && <Link className="btn-primary gap-2" href="/time-clock"><Icon name="clock" />Open time clock</Link>}</div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Working" value={working} tone="green" icon="people" /><StatCard label="Not checked in" value={count("Not Checked In")} tone="red" icon="people" /><StatCard label="Late" value={count("Late")} tone="amber" icon="clock" /><StatCard label="On leave" value={count("On Leave")} tone="blue" icon="calendar" /><StatCard label="Missing checkout" value={count("Missing Checkout")} tone="red" icon="records" /></section>
    <section className="reference-attention"><div className="reference-attention-title"><span className="text-orange-600">▲</span>Needs attention</div><div className="reference-attention-grid"><Attention count={count("Missing Checkout")} label="missing checkout" href="/workforce" action="Review" icon="records" /><Attention count={pendingCorrections} label="attendance corrections" href="/corrections" action="Review" icon="records" /><Attention count={pendingLeave} label="leave requests" href="/leave" action="Approve" icon="calendar" /></div></section>
    <SectionTabs items={[{ href: "/workforce", label: "Live" }, { href: "/timesheets", label: "Timesheets" }, { href: "/schedule", label: "Schedule" }, { href: "/corrections", label: "Corrections" }, { href: "/shifts", label: "Shifts & holidays" }]} />
    <section className="grid gap-5 xl:grid-cols-[.92fr_1.08fr]"><article className="panel overflow-hidden"><div className="reference-card-heading"><h2><Icon name="people" />Live workforce</h2><div className="flex gap-2"><label className="search-field !min-h-9 w-44"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employees..." /></label><select className="compact-select" aria-label="Filter workforce" value={state} onChange={(event) => setState(event.target.value)}><option value="">Filter</option>{["Working", "On Break", "Late", "Not Checked In", "Checked Out", "On Leave", "Missing Checkout"].map((item) => <option key={item}>{item}</option>)}</select></div></div>{rows.slice(0, 6).map(({ employee, record, currentState }) => <div className="reference-workforce-row" key={employee.id}><div className="flex min-w-0 items-center gap-3"><Avatar initials={employee.initials} /><div className="min-w-0"><b className="block truncate text-sm text-slate-950">{employee.name}</b><span className="block truncate text-xs text-slate-500">{employee.role}</span></div></div><div className="text-xs text-slate-500">{record?.checkIn ? <>Checked in<br/><b>{record.checkIn}</b></> : currentState}</div><StateBadge state={currentState} /></div>)}<Link className="m-5 inline-flex text-sm font-semibold text-blue-700" href="/employees">View full directory</Link></article>
      <div className="space-y-4"><article className="panel p-5"><h2 className="section-title flex gap-2"><Icon name="clock" />Today&apos;s timeline</h2><div className="mt-4 grid gap-5 sm:grid-cols-2"><div><small>Your shift</small><b className="mt-1 block">{firstShift ? `${firstShift.startTime} – ${firstShift.endTime}` : "No shift configured"}</b><span className="text-xs text-slate-500">{firstShift ? `${formatMinutes(timeToMinutes(firstShift.endTime) - timeToMinutes(firstShift.startTime))} · Full day` : "Current schedule"}</span></div><div className="border-l border-slate-200 pl-5"><small>Check-in progress</small><div className="mt-3 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{ width: `${scoped.length ? working / scoped.length * 100 : 0}%` }} /></div><b>{scoped.length ? Math.round(working / scoped.length * 100) : 0}%</b></div><span className="text-xs text-slate-500">{working} of {scoped.length} employees checked in</span></div></div></article><article className="panel p-5"><div className="flex justify-between"><h2 className="section-title flex gap-2"><Icon name="chart" />Attendance trend</h2><span className="text-xs">Last 7 days⌄</span></div><svg className="reference-chart mt-2" viewBox="0 0 600 225"><defs><linearGradient id="wf-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0d9398" stopOpacity=".14"/><stop offset="100%" stopColor="#0d9398" stopOpacity="0"/></linearGradient></defs>{[47,88,130,172].map((y) => <line x1="45" x2="561" y1={y} y2={y} stroke="#e5e7eb" key={y}/>) }<polygon points={`45,172 ${points} 561,172`} fill="url(#wf-fill)"/><polyline points={points} fill="none" stroke="#0d9398" strokeWidth="2.5"/>{trend.map((item, index) => { const x = 45 + index * 86; const y = 172 - item.value / max * 125; return <g key={item.date}><circle cx={x} cy={y} r="4" fill="white" stroke="#0d9398" strokeWidth="2.5"/><text x={x} y={y - 12} textAnchor="middle" className="fill-slate-900 text-[10px] font-bold">{item.value}</text><text x={x} y="196" textAnchor="middle" className="fill-slate-800 text-[10px]">{item.day}</text><text x={x} y="211" textAnchor="middle" className="fill-slate-400 text-[9px]">{item.date}</text></g>; })}</svg></article></div></section>
    <section className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Time Clock details</h2><p className="section-copy">Existing current-session details and calculations</p></div><Link className="btn-secondary" href="/attendance">Mark attendance</Link></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Scheduled shift</th><th>Clock in</th><th>Clock out</th><th>Current state</th><th>Worked</th><th>Break</th></tr></thead><tbody>{rows.map(({ employee, record, shift, currentState, activeBreak, breakMinutes, workedMinutes }) => <tr key={employee.id}><td><b>{employee.name}</b><p className="text-xs">{employee.department}</p></td><td>{shift ? `${shift.startTime}–${shift.endTime}` : "—"}</td><td>{record?.checkIn || "—"}</td><td>{record?.checkOut || "—"}</td><td>{record?.status && ["Working", "Late"].includes(currentState) ? <StatusBadge status={record.status} /> : <StateBadge state={currentState} />}</td><td>{formatMinutes(workedMinutes)}</td><td>{activeBreak ? `Active · ${formatMinutes(breakMinutes)}` : formatMinutes(breakMinutes)}</td></tr>)}</tbody></table></div></section>
  </div>;
}

function Attention({ count, label, href, action, icon }: { count: number; label: string; href: string; action: string; icon: "records" | "calendar" }) { return <div className="reference-attention-item"><span><Icon name={icon} /></span><p><b>{count}</b> {label}</p><Link href={href}>{action}</Link></div>; }
function StateBadge({ state }: { state: string }) { return <span className={`status-badge justify-center ${state === "Working" ? "status-present" : state === "Late" ? "status-late" : state === "On Leave" ? "status-leave" : state === "On Break" ? "status-break" : state.includes("Missing") ? "status-absent" : "status-inactive"}`}>{state}</span>; }
