"use client";
import { useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { useAttendance } from "@/components/attendance-provider";
import { AttendanceTimeline } from "@/components/attendance-timeline";
import { useWorkforce } from "@/components/workforce-provider";
import { EmptyState, PageHeading as BasePageHeading } from "@/components/ui";
import { breakMinutesFor, formatShortDate } from "@/lib/attendance";
import { formatMinutes, shiftDuration, timeToMinutes } from "@/lib/scheduling";
import { approvalFor, resolvedSchedule } from "@/lib/workforce";
const PageHeading = (props: Parameters<typeof BasePageHeading>[0]) => <BasePageHeading {...props} description={props.title === "My timesheets" ? "Daily timesheets based on your recorded clock activity." : props.description} />;

export default function TimesheetsPage() {
  const auth = useAuth(); const data = useAttendance(); const { schedules, approvals, reviewTimesheet } = useWorkforce(); const [note, setNote] = useState(""); const [expanded, setExpanded] = useState(""); const [notice, setNotice] = useState<{ ok: boolean; message: string }>();
  const rows = data.records.filter((record) => !!record.checkIn && (auth.role !== "manager" || auth.currentUser?.teamIds.includes(record.employeeId))).sort((a, b) => b.date.localeCompare(a.date)).map((record) => { const employee = data.employees.find((item) => item.id === record.employeeId); const resolved = resolvedSchedule(schedules, record.employeeId, record.date, data.assignments[record.employeeId], data.shifts); const scheduled = record.scheduledStart && record.scheduledEnd ? { ...(resolved || { id: `clock:${record.employeeId}:${record.date}`, employeeId: record.employeeId, date: record.date, shiftId: record.shiftId || "", status: "Scheduled" as const, createdAt: "", updatedAt: "" }), startTime: record.scheduledStart, endTime: record.scheduledEnd } : resolved; const template = data.shifts.find((item) => item.id === scheduled?.shiftId); const shift = template && scheduled ? { ...template, startTime: scheduled.startTime, endTime: scheduled.endTime } : template; const approval = approvalFor(approvals, record.employeeId, record.date); const scheduledMinutes = shift ? shiftDuration(shift) : 0; const worked = record.workedMinutes || 0; const lateMinutes = record.checkIn && scheduled ? Math.max(0, timeToMinutes(record.checkIn) - timeToMinutes(scheduled.startTime)) : 0; return { record, employee, scheduled, shift, approval, scheduledMinutes, worked, lateMinutes }; }).filter((row) => row.employee);
  const canReview = auth.role !== "employee";
  if ((() => auth.role === "employee")()) return <div className="space-y-6"><PageHeading title="My Timesheets" description="Daily time summaries from your recorded clock activity." />{rows.length ? <section className="grid gap-4 lg:grid-cols-2">{rows.map(({ record, scheduled, shift, approval, scheduledMinutes, worked, lateMinutes }) => <article className="employee-timesheet-card panel" key={`${record.employeeId}:${record.date}`}><div className="flex items-start justify-between gap-3 border-b border-slate-100 p-4"><div><b className="text-slate-950">{formatShortDate(record.date)}</b><p className="mt-1 text-xs text-slate-500">{scheduled ? `${scheduled.startTime}–${scheduled.endTime} · ${formatMinutes(scheduledMinutes)} scheduled` : "Unscheduled"}</p></div><span className={`leave-badge leave-${approval.status.toLowerCase()}`}>{approval.status}</span></div><div className="grid grid-cols-2 gap-px bg-slate-100 sm:grid-cols-4"><div><span>Worked</span><b>{formatMinutes(worked)}</b></div><div><span>Break</span><b>{formatMinutes(breakMinutesFor(record))}</b></div><div><span>Regular</span><b>{formatMinutes(Math.min(worked, scheduledMinutes))}</b></div><div><span>Overtime</span><b>{formatMinutes(record.overtimeMinutes)}</b></div></div><div className="flex items-center justify-between gap-3 px-4 py-3 text-xs"><span className={lateMinutes || record.earlyDepartureMinutes || !record.checkOut ? "text-amber-700" : "text-slate-500"}>{lateMinutes ? `${lateMinutes}m late` : record.earlyDepartureMinutes ? `${record.earlyDepartureMinutes}m early` : !record.checkOut ? "Missing checkout" : "No exceptions"}</span><button className="text-link" onClick={() => setExpanded(expanded === record.date ? "" : record.date)}>{expanded === record.date ? "Hide timeline" : "View timeline"}</button></div>{expanded === record.date && <div className="border-t border-slate-100 p-4"><AttendanceTimeline record={record} shift={shift} /></div>}</article>)}</section> : <div className="panel"><EmptyState title="No timesheets" description="Clocked attendance sessions will appear here." /></div>}</div>;
  return <div className="space-y-6"><PageHeading title={auth.role === "employee" ? "My timesheets" : auth.role === "manager" ? "Team timesheets" : "Timesheets"} description="Daily timesheets derived directly from canonical clock activity." />{notice && <div className={`notice ${notice.ok ? "notice-success" : "notice-error"}`}>{notice.message}</div>}<section className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Timesheet records</h2><p className="section-copy">{rows.length} clocked attendance sessions</p></div></div>{rows.length ? <div className="table-wrap"><table className="min-w-[1120px]"><thead><tr><th>Employee / date</th><th>Scheduled</th><th>Actual</th><th>Time summary</th><th>Exceptions</th><th>Approval</th></tr></thead><tbody>{rows.map(({ record, employee, scheduled, shift, approval, scheduledMinutes, worked, lateMinutes }) => { const key = `${record.employeeId}:${record.date}`; return <tr key={key}><td><b>{employee!.name}</b><p className="text-xs">{formatShortDate(record.date)}</p><button className="text-link mt-1" onClick={() => setExpanded(expanded === key ? "" : key)}>{expanded === key ? "Hide timeline" : "View timeline"}</button>{expanded === key && <div className="mt-3 min-w-72"><AttendanceTimeline record={record} shift={shift} /></div>}</td><td>{scheduled ? `${scheduled.startTime}–${scheduled.endTime}` : "Unscheduled"}<p className="text-xs">{formatMinutes(scheduledMinutes)}</p></td><td>{record.checkIn || "—"}–{record.checkOut || "—"}</td><td><div className="timesheet-metrics"><span>Break <b>{formatMinutes(breakMinutesFor(record))}</b></span><span>Worked <b>{formatMinutes(worked)}</b></span><span>Regular <b>{formatMinutes(Math.min(worked, scheduledMinutes))}</b></span><span>Overtime <b>{formatMinutes(record.overtimeMinutes)}</b></span></div></td><td>{lateMinutes ? `${lateMinutes}m late` : record.earlyDepartureMinutes ? `${record.earlyDepartureMinutes}m early` : !record.checkOut ? "Missing checkout" : "None"}</td><td><span className={`leave-badge leave-${approval.status.toLowerCase()}`}>{approval.status}</span>{canReview && auth.currentUser?.employeeId !== record.employeeId && <div className="mt-2 min-w-48"><input className="compact-select w-full" placeholder="Review note" value={note} onChange={(event) => setNote(event.target.value)} /><div className="mt-1"><button className="table-action text-emerald-700" onClick={() => setNotice(reviewTimesheet(record.employeeId, record.date, "Approved", note))}>Approve</button><button className="table-action text-rose-600" onClick={() => setNotice(reviewTimesheet(record.employeeId, record.date, "Rejected", note))}>Reject</button></div></div>}<p className="mt-1 text-xs">{approval.note}</p></td></tr>; })}</tbody></table></div> : <EmptyState title="No timesheets" description="Clocked attendance sessions will appear here." />}</section></div>;
}
