"use client";
import { useEffect, useMemo, useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { Icon } from "@/components/icons";
import { useOperations } from "@/components/operations-provider";
import { Avatar, EmptyState, StatCard, StatusBadge } from "@/components/ui";
import { AttendanceStatus, attendanceStatusLabels, attendanceStatuses, formatShortDate, getMonthKey, isAttendedStatus } from "@/lib/attendance";
import { downloadCsv } from "@/lib/operations";
import { formatMinutes, shiftDisplayName } from "@/lib/scheduling";

const reportTypes = ["Attendance Report", "Absence Report", "Late Arrivals Report", "Overtime Report", "Leave Utilization Report", "Department Attendance Report", "Employee Attendance Report"];

export default function ReportsPage() {
  const { role, currentUser } = useAuth(); const { settings } = useOperations(); const { records: authorizedRecords, allEmployees: authorizedEmployees, allShifts, assignments } = useAttendance();
  useEffect(() => { document.body.classList.toggle("employee-reports", role === "employee"); return () => document.body.classList.remove("employee-reports"); }, [role]);
  const employees = role === "manager" ? authorizedEmployees.filter((item) => currentUser?.teamIds.includes(item.id)) : authorizedEmployees; const allowedIds = new Set(employees.map((item) => item.id)); const records = authorizedRecords.filter((item) => allowedIds.has(item.employeeId));
  const [report, setReport] = useState(reportTypes[0]); const [start, setStart] = useState(`${getMonthKey()}-01`); const [end, setEnd] = useState(""); const [employeeId, setEmployeeId] = useState(""); const [department, setDepartment] = useState(""); const [status, setStatus] = useState<AttendanceStatus | "">(""); const departments = [...new Set(employees.map((item) => item.department))].sort();
  const filtered = useMemo(() => records.filter((item) => { const employee = employees.find((entry) => entry.id === item.employeeId); if (!employee || (start && item.date < start) || (end && item.date > end) || (employeeId && item.employeeId !== employeeId) || (department && employee.department !== department) || (status && item.status !== status)) return false; if (report === "Absence Report" && item.status !== "absent") return false; if (report === "Late Arrivals Report" && item.status !== "late") return false; if (report === "Overtime Report" && !item.overtimeMinutes) return false; return true; }).sort((a, b) => b.date.localeCompare(a.date)), [records, employees, start, end, employeeId, department, status, report]);
  const attended = filtered.length ? Math.round(filtered.filter((item) => isAttendedStatus(item.status)).length / filtered.length * 100) : 0; const absent = filtered.filter((item) => item.status === "absent").length; const late = filtered.filter((item) => item.status === "late").length; const overtime = filtered.reduce((sum, item) => sum + (item.overtimeMinutes || 0), 0);
  const days = useMemo(() => Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() - (6 - offset)); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; const day = filtered.filter((item) => item.date === key); return { day: date.toLocaleDateString("en-US", { weekday: "short" }), date: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }), value: day.length ? Math.round(day.filter((item) => isAttendedStatus(item.status)).length / day.length * 100) : 0 }; }), [filtered]);
  const departmentRates = departments.map((name) => { const ids = new Set(employees.filter((item) => item.department === name).map((item) => item.id)); const scoped = filtered.filter((item) => ids.has(item.employeeId)); return { name, value: scoped.length ? Math.round(scoped.filter((item) => isAttendedStatus(item.status)).length / scoped.length * 100) : 0 }; }).slice(0, 5); const points = days.map((item, index) => `${44 + index * 74},${161 - item.value * 1.15}`).join(" ");
  const exportRows = () => downloadCsv("northstar-attendance-report.csv", [["Date", "Employee ID", "Employee", "Department", "Status", "Shift", "Check In", "Check Out", "Worked Minutes", "Overtime Minutes", "Source"], ...filtered.map((item) => { const employee = employees.find((entry) => entry.id === item.employeeId); const shift = allShifts.find((entry) => entry.id === (item.shiftId || assignments[item.employeeId])); return [item.date, item.employeeId, employee?.name, employee?.department, item.status, shift ? shiftDisplayName(shift) : undefined, item.checkIn, item.checkOut, item.workedMinutes, item.overtimeMinutes, item.source]; })]);
  if (role === "employee") return <div className="space-y-6 print:p-0"><div className="flex justify-end print:hidden"><button className="btn-secondary" onClick={exportRows}>Export my summary</button></div><section className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Attendance" value={`${attended}%`} tone="green" icon="check" /><StatCard label="Absent" value={absent} tone="red" icon="people" /><StatCard label="Late" value={late} tone="amber" icon="clock" /><StatCard label="Overtime" value={formatMinutes(overtime)} tone="blue" icon="clock" /></section><article className="panel p-4"><div className="flex justify-between"><div><h2 className="section-title">My attendance trend</h2><p className="section-copy">Your attendance rate across the last seven days</p></div><span className="text-xs text-slate-500">Last 7 days</span></div><svg className="reference-chart mt-3" viewBox="0 0 520 210">{[46,84,123,161].map((y) => <line x1="44" x2="488" y1={y} y2={y} stroke="#e5e7eb" key={y}/>)}<polyline points={points} fill="none" stroke="#0d9398" strokeWidth="2.5"/>{days.map((item,index) => { const x=44+index*74; const y=161-item.value*1.15; return <g key={item.date}><circle cx={x} cy={y} r="4" fill="white" stroke="#0d9398" strokeWidth="2.5"/><text x={x} y={y-10} textAnchor="middle" className="fill-slate-900 text-[10px]">{item.value}%</text><text x={x} y="184" textAnchor="middle" className="fill-slate-800 text-[9px]">{item.day}</text><text x={x} y="199" textAnchor="middle" className="fill-slate-400 text-[8px]">{item.date}</text></g>; })}</svg></article><article className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Attendance records</h2><p className="section-copy">Only your authorized attendance history</p></div></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Status</th><th>Check in</th><th>Check out</th><th>Worked</th><th>Overtime</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.date}><td>{formatShortDate(item.date)}</td><td><StatusBadge status={item.status} /></td><td>{item.checkIn || "—"}</td><td>{item.checkOut || (item.checkIn ? "Not checked out" : "—")}</td><td>{formatMinutes(item.workedMinutes)}</td><td>{formatMinutes(item.overtimeMinutes)}</td></tr>)}</tbody></table></div> : <EmptyState title="No attendance records" description="Adjust the date range to find your records." />}</article></div>;
  return <div className="space-y-5 print:p-0"><header className="hidden print:block"><h1>{settings.organizationName}</h1><h2>{report}</h2></header>
    <div className="filter-bar print:hidden !flex-wrap"><label className="filter-field"><span>Date range · From</span><input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label className="filter-field"><span>To</span><input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label><label className="filter-field"><span>Department</span><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label><label className="filter-field"><span>Employee</span><select value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">All employees</option>{employees.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="filter-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value as AttendanceStatus | "")}><option value="">All statuses</option>{attendanceStatuses.map((item) => <option key={item} value={item}>{attendanceStatusLabels[item]}</option>)}</select></label><button className="btn-primary" onClick={() => setReport("Attendance Report")}>Apply filters</button><button className="btn-secondary" onClick={exportRows}>Export CSV</button></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Attendance" value={`${attended}%`} tone="green" icon="check" /><StatCard label="Absent" value={absent} tone="red" icon="people" /><StatCard label="Late" value={late} tone="amber" icon="clock" /><StatCard label="Overtime" value={formatMinutes(overtime)} tone="blue" icon="clock" /></section>
    <section className="grid gap-5 xl:grid-cols-[1fr_1.04fr]"><article className="panel p-4"><div className="flex justify-between"><h2 className="section-title flex gap-2"><Icon name="chart" />Attendance trend</h2><span className="text-xs">Last 7 days⌄</span></div><svg className="reference-chart" viewBox="0 0 520 210">{[46,84,123,161].map((y) => <line x1="44" x2="488" y1={y} y2={y} stroke="#e5e7eb" key={y}/>)}<polyline points={points} fill="none" stroke="#0d9398" strokeWidth="2.5"/>{days.map((item,index) => { const x=44+index*74; const y=161-item.value*1.15; return <g key={item.date}><circle cx={x} cy={y} r="4" fill="white" stroke="#0d9398" strokeWidth="2.5"/><text x={x} y={y-10} textAnchor="middle" className="fill-slate-900 text-[10px]">{item.value}%</text><text x={x} y="184" textAnchor="middle" className="fill-slate-800 text-[9px]">{item.day}</text><text x={x} y="199" textAnchor="middle" className="fill-slate-400 text-[8px]">{item.date}</text></g>; })}</svg></article><article className="panel p-4"><div className="flex justify-between"><h2 className="section-title flex gap-2"><Icon name="chart" />Department comparison</h2><span className="text-xs">By attendance %⌄</span></div><div className="mt-6 space-y-4">{departmentRates.map((item) => <div className="grid grid-cols-[7rem_1fr_3rem] items-center gap-3 text-xs" key={item.name}><span className="text-right">{item.name}</span><div className="h-4 bg-slate-50"><div className="h-full rounded-r-sm bg-teal-600" style={{ width: `${item.value}%` }} /></div><b>{item.value}%</b></div>)}</div></article></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="panel overflow-hidden"><div className="reference-card-heading"><h2><Icon name="records" />Report preview</h2><button className="btn-secondary !min-h-9 text-xs print:hidden" onClick={() => window.print()}>Print report</button></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Department</th><th>Status</th><th>Check in/out</th><th>Worked</th></tr></thead><tbody>{filtered.slice(0, 8).map((item) => { const employee = employees.find((entry) => entry.id === item.employeeId)!; return <tr key={`${item.employeeId}-${item.date}`}><td>{formatShortDate(item.date)}</td><td><div className="flex items-center gap-2"><Avatar initials={employee.initials} /><b>{employee.name}</b></div></td><td>{employee.department}</td><td><StatusBadge status={item.status} /></td><td>{item.checkIn || "—"} – {item.checkOut || "—"}</td><td>{formatMinutes(item.workedMinutes)}</td></tr>; })}</tbody></table></div> : <EmptyState title="No report records" description="Adjust the filters to find authorized records." />}</article><article className="panel overflow-hidden"><div className="reference-card-heading"><h2>Saved reports</h2></div><div className="divide-y divide-slate-100">{reportTypes.slice(0, 4).map((item, index) => <button className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-slate-50" onClick={() => setReport(item)} key={item}><span className={`stat-icon h-9 w-9 ${["stat-green","stat-amber","stat-blue","stat-violet"][index]}`}><Icon name={index === 1 ? "clock" : "records"} /></span><span className="flex-1"><b className="block text-sm">{item.replace(" Report", "")}</b><small className="text-slate-500">Current filters · Live data</small></span><span>›</span></button>)}</div></article></section>
  </div>;
}
