"use client";
import { useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { Avatar, EmptyState, PageHeading, ProgressBar } from "@/components/ui";
import { getMonthKey, percentageFor } from "@/lib/attendance";
export default function MonthlyPage() {
  const { records, employees } = useAttendance(); const [month, setMonth] = useState(getMonthKey); const monthRecords = records.filter((record) => record.date.startsWith(month));
  return <div className="space-y-6"><PageHeading title="Monthly overview" description="Compare attendance outcomes across your team." action={<label className="date-field"><span>Month</span><input type="month" value={month} max={getMonthKey()} onChange={(event) => setMonth(event.target.value)} /></label>} />
    <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Team summary</h2><p className="section-copy">{monthRecords.length} attendance records this month</p></div></div>{monthRecords.length === 0 ? <EmptyState title="No records for this month" description="Choose another month or start marking attendance." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Present</th><th>Absent</th><th>Late</th><th>Leave</th><th className="min-w-48">Attendance</th></tr></thead><tbody>{employees.map((employee) => { const own = monthRecords.filter((record) => record.employeeId === employee.id); const count = (status: string) => own.filter((record) => record.status === status).length; const pct = percentageFor(records, employee.id, month); return <tr key={employee.id}><td><div className="flex items-center gap-3"><Avatar initials={employee.initials} /><div><p className="font-semibold text-slate-900">{employee.name}</p><p className="text-xs text-slate-500">{employee.department}</p></div></div></td><td className="font-semibold text-emerald-700">{count("present")}</td><td className="font-semibold text-rose-700">{count("absent")}</td><td className="font-semibold text-amber-700">{count("late")}</td><td className="font-semibold text-blue-700">{count("leave")}</td><td><div className="flex items-center gap-3"><div className="min-w-24 flex-1"><ProgressBar value={pct} /></div><span className="w-10 text-right font-semibold">{pct}%</span></div></td></tr>; })}</tbody></table></div>}</div></div>;
}
