"use client";
import Link from "next/link";
import { useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { useOperations } from "@/components/operations-provider";
import { useWorkforce } from "@/components/workforce-provider";
import { Icon } from "@/components/icons";
import { PageHeading, ProgressBar, StatCard, StatusBadge } from "@/components/ui";
import { breakMinutesFor, formatLongDate, getToday, percentageFor, recordsForDate } from "@/lib/attendance";
import { formatMinutes, isScheduledDate, timeToMinutes } from "@/lib/scheduling";
const currentTime = () => new Date().toTimeString().slice(0, 5);

export default function DashboardPage() {
  const { role, currentUser } = useAuth();
  const data = useAttendance();
  const { corrections, addAudit } = useOperations(); const { approvals } = useWorkforce();
  const { records, employees, leaveRequests, balances, shifts, assignments, holidays, workingDays, checkIn, checkOut, startBreak, endBreak } = data;
  const [notice, setNotice] = useState<{ ok: boolean; message: string }>();
  const today = getToday();
  const active = employees.filter((employee) => employee.status === "Active" && (role !== "manager" || currentUser?.teamIds.includes(employee.id)));
  const todayRecords = recordsForDate(records, today).filter((record) => active.some((employee) => employee.id === record.employeeId));
  const leaveIds = new Set(leaveRequests.filter((request) => request.status === "Approved" && request.startDate <= today && request.endDate >= today && active.some((employee) => employee.id === request.employeeId)).map((request) => request.employeeId));
  const scheduled = active.filter((employee) => isScheduledDate(today, workingDays, holidays, shifts.find((shift) => shift.id === assignments[employee.id])));
  const working = todayRecords.filter((record) => record.checkIn && !record.checkOut).length;
  const checkedOut = todayRecords.filter((record) => record.checkOut).length;
  const late = todayRecords.filter((record) => record.status === "late").length;
  const notIn = scheduled.filter((employee) => !leaveIds.has(employee.id) && !todayRecords.some((record) => record.employeeId === employee.id && record.checkIn)).length;
  const missingOut = todayRecords.filter((record) => { const shift = shifts.find((item) => item.id === (record.shiftId || assignments[record.employeeId])); return record.checkIn && !record.checkOut && shift && timeToMinutes(currentTime()) > timeToMinutes(shift.endTime); }).length;
  const pendingTimesheets = records.filter((record) => active.some((employee) => employee.id === record.employeeId) && record.checkIn && !approvals.some((item) => item.employeeId === record.employeeId && item.date === record.date && item.status === "Approved")).length; const pendingCorrections = corrections.filter((item) => item.status === "Pending" && active.some((employee) => employee.id === item.employeeId)).length; const pendingLeave = leaveRequests.filter((item) => item.status.startsWith("Pending") && active.some((employee) => employee.id === item.employeeId)).length;
  const trend = Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() - (6 - offset)); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; const day = records.filter((record) => record.date === key); return { label: date.toLocaleDateString("en-US", { weekday: "short" }), value: day.length ? Math.round(day.filter((record) => record.status === "present" || record.status === "late").length / day.length * 100) : 0 }; });

  if (role === "employee") {
    const employeeId = currentUser?.employeeId;
    const employee = active.find((item) => item.id === employeeId);
    const record = todayRecords.find((item) => item.employeeId === employeeId);
    const shift = shifts.find((item) => item.id === (record?.shiftId || (employeeId ? assignments[employeeId] : "")));
    const holiday = holidays.find((item) => item.date === today);
    const isWorkday = !!shift && isScheduledDate(today, workingDays, holidays, shift);
    const onLeave = !!employeeId && (leaveIds.has(employeeId) || record?.source === "approved-leave");
    const activeBreak = record?.breaks?.find((item) => !item.end); const liveBreak = breakMinutesFor(record, currentTime()); const liveWorked = record?.workedMinutes ?? (record?.checkIn ? Math.max(0, timeToMinutes(currentTime()) - timeToMinutes(record.checkIn) - liveBreak) : 0);
    const clock = (kind: "in" | "out" | "break-start" | "break-end") => { if (!employeeId) return; const result = kind === "in" ? checkIn(employeeId, today, currentTime()) : kind === "out" ? checkOut(employeeId, today, currentTime()) : kind === "break-start" ? startBreak(employeeId, today, currentTime()) : endBreak(employeeId, today, currentTime()); setNotice(result); if (result.ok && kind.startsWith("break")) addAudit(kind === "break-start" ? "break started" : "break ended", "attendance", `${employeeId}:${today}`, result.message); };
    const recent = records.filter((item) => item.employeeId === employeeId).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5);
    const state = onLeave ? "On approved leave" : !isWorkday ? (holiday?.name || "Non-working day") : record?.checkOut ? "Workday complete" : record?.checkIn ? `Checked in at ${record.checkIn}` : "Not checked in yet";
    return <div className="space-y-6">
      <PageHeading eyebrow={formatLongDate(today)} title={`Good day, ${employee?.name.split(" ")[0] || "there"}`} description="Your attendance, schedule, and time off in one place." action={<Link className="btn-secondary" href="/attendance">View my attendance</Link>} />
      {notice && <div className={`notice ${notice.ok ? "notice-success" : "notice-error"}`}>{notice.message}</div>}
      <section className="attendance-hero" aria-label="Today's attendance actions"><div className="attendance-hero-copy"><div className="flex flex-wrap items-center gap-2"><span className="hero-kicker">Today&apos;s attendance</span>{record && <StatusBadge status={record.status} />}{activeBreak && <span className="status-badge status-break">On break since {activeBreak.start}</span>}</div><h2>{activeBreak ? "On break" : state}</h2><p>{shift ? `${shift.name} · ${shift.startTime}–${shift.endTime}` : "No active shift assigned"}</p>{!isWorkday && !onLeave && <p className="hero-note">Normal attendance is not expected today, so clock actions are unavailable.</p>}</div><div className="attendance-actions"><button className="clock-button clock-in" disabled={!employee || !shift || !isWorkday || onLeave || !!record?.checkIn} onClick={() => clock("in")}><Icon name="check" />Check In</button>{activeBreak ? <button className="clock-button break-button" onClick={() => clock("break-end")}>End Break</button> : <button className="clock-button break-button" disabled={!record?.checkIn || !!record.checkOut} onClick={() => clock("break-start")}>Start Break</button>}<button className="clock-button clock-out" disabled={!employee || onLeave || !record?.checkIn || !!record.checkOut || !!activeBreak} onClick={() => clock("out")}><Icon name="clock" />Check Out</button></div><div className="attendance-metrics"><div><span>Check in</span><b>{record?.checkIn || "—"}</b></div><div><span>Check out</span><b>{record?.checkOut || "—"}</b></div><div><span>Worked</span><b>{formatMinutes(liveWorked)}</b></div><div><span>Break</span><b>{formatMinutes(liveBreak)}</b></div><div><span>Overtime</span><b>{formatMinutes(record?.overtimeMinutes)}</b></div></div></section>
      <section className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Recent attendance</h2><p className="section-copy">Your latest recorded workdays</p></div><Link className="text-link" href="/reports">View report</Link></div><div className="divide-y divide-slate-100">{recent.map((item) => <div className="flex items-center gap-3 px-5 py-4" key={item.date}><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{formatLongDate(item.date)}</p><p className="text-xs text-slate-500">{item.checkIn || "—"} to {item.checkOut || "—"} · {formatMinutes(item.workedMinutes)}</p></div><StatusBadge status={item.status} /></div>)}</div></div><div className="panel p-5"><h2 className="section-title">Leave balance</h2><p className="section-copy">Available days by leave type</p><div className="mt-5 space-y-4">{Object.entries(employeeId ? balances[employeeId] || {} : {}).map(([type, value]) => <div key={type}><div className="mb-1.5 flex justify-between text-sm"><span className="font-medium text-slate-600">{type}</span><b>{value} days</b></div><ProgressBar value={Math.min(100, Number(value) * 5)} /></div>)}</div><Link className="btn-secondary mt-6 w-full" href="/leave">Manage leave</Link></div></section>
    </div>;
  }

  const manager = role === "manager"; const scope = manager ? "your assigned team" : "the organization";
  return <div className="space-y-6"><PageHeading eyebrow={formatLongDate(today)} title={manager ? "Manager dashboard" : "Workforce dashboard"} description={`A live operational view of ${scope}.`} action={<Link className="btn-primary" href="/attendance">{manager ? "Team attendance" : "Manage attendance"}</Link>} />
    <section className="panel p-5"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="section-title">Today&apos;s attendance</h2><p className="section-copy">Live attendance across {scope}</p></div><span className="status-badge status-information">Live</span></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><StatCard label="Currently working" value={working} tone="green" icon="people" /><StatCard label="Not checked in" value={notIn} tone="blue" icon="clock" /><StatCard label="Checked out" value={checkedOut} tone="slate" icon="check" /><StatCard label="Late" value={late} tone="amber" icon="clock" /><StatCard label="Missing checkout" value={missingOut} tone="red" icon="x" /></div></section>
    <section className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="In scope" value={active.length} tone="blue" icon="people" /><StatCard label="Checked in" value={todayRecords.filter((record) => record.checkIn).length} tone="green" icon="check" /><StatCard label="On leave" value={leaveIds.size} tone="violet" icon="calendar" /><StatCard label="Attention required" value={late + missingOut + notIn} tone="amber" icon="clock" /></section>
    <section className="grid gap-6 lg:grid-cols-2"><article className="panel p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-rose-600">Needs attention</p><div className="mt-4 divide-y divide-slate-100"><div className="flex justify-between py-3 text-sm"><span>Missing checkouts</span><b>{missingOut}</b></div><div className="flex justify-between py-3 text-sm"><span>Late arrivals</span><b>{late}</b></div><div className="flex justify-between py-3 text-sm"><span>Attendance exceptions</span><b>{notIn + missingOut}</b></div></div><Link className="text-link mt-3 inline-flex" href="/workforce">Open live workforce</Link></article><article className="panel p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-indigo-600">Needs approval</p><div className="mt-4 divide-y divide-slate-100"><div className="flex justify-between py-3 text-sm"><span>Timesheets</span><b>{pendingTimesheets}</b></div><div className="flex justify-between py-3 text-sm"><span>Leave requests</span><b>{pendingLeave}</b></div><div className="flex justify-between py-3 text-sm"><span>Corrections</span><b>{pendingCorrections}</b></div></div><Link className="text-link mt-3 inline-flex" href="/timesheets">Review timesheets</Link></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div className="panel p-5"><div className="flex items-start justify-between"><div><h2 className="section-title">Attendance trend</h2><p className="section-copy">Authorized attendance rate over seven days</p></div><span className="text-xs font-semibold text-slate-500">7 days</span></div><div className="mt-6 grid h-44 grid-cols-7 items-end gap-2 sm:gap-4">{trend.map((item) => <div className="flex h-full flex-col justify-end gap-2 text-center" key={item.label}><span className="text-[10px] font-semibold text-slate-500">{item.value}%</span><div className="trend-bar mx-auto w-full max-w-12 rounded-t-md" style={{ height: `${Math.max(4, item.value)}%` }} /><span className="text-[10px] text-slate-400">{item.label}</span></div>)}</div></div><div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Team status</h2><p className="section-copy">Only employees in your authorized scope</p></div></div><div className="divide-y divide-slate-100">{active.slice(0, 7).map((employee) => { const record = todayRecords.find((item) => item.employeeId === employee.id); const status = leaveIds.has(employee.id) ? "leave" : record?.status; return <div className="flex items-center gap-3 px-5 py-3.5" key={employee.id}><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{employee.name}</p><p className="truncate text-xs text-slate-500">{employee.department} · {record?.checkIn ? `In ${record.checkIn}` : "Not checked in"}</p></div>{status ? <StatusBadge status={status} /> : <span className="status-badge status-pending">Pending</span>}</div>; })}</div></div></section>
    <section className="panel p-5"><div className="mb-5"><h2 className="section-title">Attendance performance</h2><p className="section-copy">Scheduled working days in the current record history</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.slice(0, 6).map((employee) => { const shift = shifts.find((item) => item.id === assignments[employee.id]); const pct = percentageFor(records, employee.id, undefined, (date) => isScheduledDate(date, workingDays, holidays, shift)); return <div key={employee.id}><div className="mb-1.5 flex justify-between text-sm"><span className="truncate font-medium text-slate-700">{employee.name}</span><b>{pct}%</b></div><ProgressBar value={pct} /></div>; })}</div></section>
  </div>;
}
