"use client";
import { useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { Avatar, EmptyState, PageHeading, StatusBadge } from "@/components/ui";
import { AttendanceStatus, attendanceStatuses, formatShortDate } from "@/lib/attendance";
export default function RecordsPage() {
  const { records, employees } = useAttendance(); const [date, setDate] = useState(""); const [department, setDepartment] = useState(""); const [status, setStatus] = useState<AttendanceStatus | "">(""); const departments = [...new Set(employees.map((employee) => employee.department))].sort();
  const filtered = records.filter((record) => { const employee = employees.find((item) => item.id === record.employeeId); return employee && (!date || record.date === date) && (!department || employee.department === department) && (!status || record.status === status); }).sort((a, b) => b.date.localeCompare(a.date) || a.employeeId.localeCompare(b.employeeId));
  return <div className="space-y-6"><PageHeading title="Attendance records" description="Review and filter all saved employee attendance records." /><div className="filter-bar"><label className="filter-field"><span>Date</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="filter-field"><span>Department</span><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label><label className="filter-field"><span>Attendance status</span><select value={status} onChange={(event) => setStatus(event.target.value as AttendanceStatus | "")}><option value="">All statuses</option>{attendanceStatuses.map((item) => <option key={item} value={item}>{item[0].toUpperCase() + item.slice(1)}</option>)}</select></label></div>
    <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Records</h2><p className="section-copy">{filtered.length} results</p></div></div>{filtered.length === 0 ? <EmptyState title={records.length ? "No filtered results" : "No attendance records"} description={records.length ? "Try changing or clearing your filters." : "Mark attendance to create your first record."} /> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Department</th><th>Status</th></tr></thead><tbody>{filtered.map((record) => { const employee = employees.find((item) => item.id === record.employeeId)!; return <tr key={`${record.date}-${record.employeeId}`}><td className="whitespace-nowrap font-medium">{formatShortDate(record.date)}</td><td><div className="flex items-center gap-3"><Avatar initials={employee.initials} /><div><p className="font-semibold text-slate-900">{employee.name}</p><p className="text-xs text-slate-500">{employee.id}</p></div></div></td><td>{employee.department}</td><td><div className="flex items-center gap-2"><StatusBadge status={record.status} />{record.source === "approved-leave" && <span className="text-xs text-slate-400">Approved</span>}</div></td></tr>; })}</tbody></table></div>}</div></div>;
}
