"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Employee, employees as seedEmployees } from "@/data/employees";
import { AttendanceRecord, AttendanceStatus, createPracticeRecords, getToday } from "@/lib/attendance";
import { LeaveBalance, LeaveRequest, LeaveStatus, datesInclusive, defaultBalance, deriveLeaveBalances } from "@/lib/leave";

export const STORAGE_KEYS = { employees: "northstar-employees-v1", attendance: "northstar-attendance-records-v1", leaves: "northstar-leave-requests-v1", balances: "northstar-leave-balances-v1" } as const;
type EmployeeInput = Omit<Employee, "deletedAt">;
type ContextValue = { employees: Employee[]; activeEmployees: Employee[]; records: AttendanceRecord[]; leaveRequests: LeaveRequest[]; balances: Record<string, LeaveBalance>; ready: boolean; markAttendance: (employeeId: string, date: string, status: AttendanceStatus) => void; addEmployee: (employee: EmployeeInput) => void; updateEmployee: (originalId: string, employee: EmployeeInput) => void; deleteEmployee: (id: string) => void; setEmployeeActive: (id: string, active: boolean) => void; addLeaveRequest: (request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => void; updateLeaveStatus: (id: string, status: LeaveStatus) => void };
const AttendanceContext = createContext<ContextValue | null>(null);
const readArray = <T,>(key: string, fallback: T[], guard: (item: unknown) => item is T) => { try { const value = window.localStorage.getItem(key); if (!value) return fallback; const parsed: unknown = JSON.parse(value); return Array.isArray(parsed) && parsed.every(guard) ? parsed : fallback; } catch { return fallback; } };
const isEmployee = (value: unknown): value is Employee => !!value && typeof value === "object" && typeof (value as Employee).id === "string" && typeof (value as Employee).email === "string";
const isRecord = (value: unknown): value is AttendanceRecord => !!value && typeof value === "object" && typeof (value as AttendanceRecord).employeeId === "string" && /^\d{4}-\d{2}-\d{2}$/.test(String((value as AttendanceRecord).date)) && ["present", "absent", "late", "leave"].includes(String((value as AttendanceRecord).status));
const isLeave = (value: unknown): value is LeaveRequest => !!value && typeof value === "object" && typeof (value as LeaveRequest).id === "string" && ["Pending", "Approved", "Rejected"].includes(String((value as LeaveRequest).status));

export function AttendanceProvider({ children }: { children: React.ReactNode }) {
  const [employees, setEmployees] = useState<Employee[]>([]); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>([]); const [balancePolicies, setBalancePolicies] = useState<Record<string, LeaveBalance>>({}); const [ready, setReady] = useState(false);
  useEffect(() => { queueMicrotask(() => { const savedEmployees = readArray(STORAGE_KEYS.employees, seedEmployees, isEmployee); const savedLeaves = readArray(STORAGE_KEYS.leaves, [], isLeave); setEmployees(savedEmployees); setRecords(readArray(STORAGE_KEYS.attendance, createPracticeRecords(), isRecord)); setLeaveRequests(savedLeaves); try { const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.balances) || "{}"); setBalancePolicies(saved && typeof saved === "object" ? saved : {}); } catch { setBalancePolicies({}); } setReady(true); }); }, []);
  const balances = useMemo(() => deriveLeaveBalances(employees.map((employee) => employee.id), balancePolicies, leaveRequests), [employees, balancePolicies, leaveRequests]);
  useEffect(() => { if (!ready) return; try { window.localStorage.setItem(STORAGE_KEYS.employees, JSON.stringify(employees)); window.localStorage.setItem(STORAGE_KEYS.attendance, JSON.stringify(records)); window.localStorage.setItem(STORAGE_KEYS.leaves, JSON.stringify(leaveRequests)); window.localStorage.setItem(STORAGE_KEYS.balances, JSON.stringify(balances)); } catch { /* The application remains usable without persistence. */ } }, [ready, employees, records, leaveRequests, balances]);
  const markAttendance = useCallback((employeeId: string, date: string, status: AttendanceStatus) => setRecords((current) => [...current.filter((record) => !(record.employeeId === employeeId && record.date === date)), { employeeId, date, status, source: "manual" }]), []);
  const addEmployee = useCallback((employee: EmployeeInput) => { setEmployees((current) => [...current, employee]); setBalancePolicies((current) => ({ ...current, [employee.id]: defaultBalance() })); }, []);
  const updateEmployee = useCallback((originalId: string, employee: EmployeeInput) => { setEmployees((current) => current.map((item) => item.id === originalId ? employee : item)); if (originalId !== employee.id) { setRecords((current) => current.map((record) => record.employeeId === originalId ? { ...record, employeeId: employee.id } : record)); setLeaveRequests((current) => current.map((request) => request.employeeId === originalId ? { ...request, employeeId: employee.id } : request)); setBalancePolicies((current) => { const next = { ...current, [employee.id]: current[originalId] || defaultBalance() }; delete next[originalId]; return next; }); } }, []);
  const deleteEmployee = useCallback((id: string) => setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, deletedAt: new Date().toISOString() } : employee)), []);
  const setEmployeeActive = useCallback((id: string, active: boolean) => setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, status: active ? "Active" : "Inactive" } : employee)), []);
  const addLeaveRequest = useCallback((request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => setLeaveRequests((current) => [...current, { ...request, id: crypto.randomUUID(), requestDate: getToday(), status: "Pending" }]), []);
  const updateLeaveStatus = useCallback((id: string, status: LeaveStatus) => { const request = leaveRequests.find((item) => item.id === id); if (!request || request.status === status) return; setLeaveRequests((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setRecords((attendance) => { const withoutGenerated = attendance.filter((record) => record.leaveRequestId !== id); if (status !== "Approved") return withoutGenerated; const occupied = new Set(withoutGenerated.filter((record) => record.employeeId === request.employeeId).map((record) => record.date)); const generated = datesInclusive(request.startDate, request.endDate).filter((date) => !occupied.has(date)).map((date): AttendanceRecord => ({ employeeId: request.employeeId, date, status: "leave", source: "approved-leave", leaveRequestId: id })); return [...withoutGenerated, ...generated]; }); }, [leaveRequests]);
  const visibleEmployees = useMemo(() => employees.filter((employee) => !employee.deletedAt), [employees]); const activeEmployees = useMemo(() => visibleEmployees.filter((employee) => employee.status === "Active"), [visibleEmployees]);
  const value = useMemo(() => ({ employees: visibleEmployees, activeEmployees, records, leaveRequests, balances, ready, markAttendance, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, addLeaveRequest, updateLeaveStatus }), [visibleEmployees, activeEmployees, records, leaveRequests, balances, ready, markAttendance, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, addLeaveRequest, updateLeaveStatus]);
  return <AttendanceContext.Provider value={value}>{children}</AttendanceContext.Provider>;
}
export function useAttendance() { const context = useContext(AttendanceContext); if (!context) throw new Error("useAttendance must be used within AttendanceProvider"); return context; }
