"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Employee, employees as seedEmployees } from "@/data/employees";
import { AttendanceRecord, AttendanceStatus, applyManualAttendanceStatus, breakMinutesFor, createPracticeRecords, getToday, normalizeAttendanceRecords } from "@/lib/attendance";
import { LeaveBalance, LeaveRequest, LeaveStatus, datesInclusive, defaultBalance, deriveLeaveBalances } from "@/lib/leave";
import { Holiday, Shift, calculateTimeMetrics, isLateCheckIn, isScheduledDate, reconcileClockStatuses, timeToMinutes } from "@/lib/scheduling";
import { seedShifts } from "@/data/schedules";
import { useAuth } from "@/components/auth-provider";
import { getVisibleAttendance, getVisibleEmployees, getVisibleLeaveRequests } from "@/lib/auth";
import { ScheduleInstance, WORKFORCE_KEYS } from "@/lib/workforce";

export const STORAGE_KEYS = { employees: "northstar-employees-v1", attendance: "northstar-attendance-records-v1", leaves: "northstar-leave-requests-v1", balances: "northstar-leave-balances-v1", shifts: "northstar-shifts-v1", assignments: "northstar-employee-shifts-v1", holidays: "northstar-holidays-v1", workingDays: "northstar-working-days-v1" } as const;
type EmployeeInput = Omit<Employee, "deletedAt">;
type OperationResult = { ok: boolean; message: string };
type ContextValue = { employees: Employee[]; allEmployees: Employee[]; activeEmployees: Employee[]; records: AttendanceRecord[]; leaveRequests: LeaveRequest[]; balances: Record<string, LeaveBalance>; shifts: Shift[]; allShifts: Shift[]; assignments: Record<string, string>; holidays: Holiday[]; workingDays: number[]; ready: boolean; markAttendance: (employeeId: string, date: string, status: AttendanceStatus) => void; checkIn: (employeeId: string, date: string, time: string) => OperationResult; checkOut: (employeeId: string, date: string, time: string) => OperationResult; addEmployee: (employee: EmployeeInput) => void; updateEmployee: (originalId: string, employee: EmployeeInput) => void; deleteEmployee: (id: string) => void; setEmployeeActive: (id: string, active: boolean) => void; setEmployeeShift: (employeeId: string, shiftId: string) => void; addLeaveRequest: (request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => void; updateLeaveStatus: (id: string, status: LeaveStatus) => void; addShift: (shift: Omit<Shift, "id">) => void; updateShift: (id: string, shift: Omit<Shift, "id">) => void; deleteShift: (id: string) => void; setShiftActive: (id: string, active: boolean) => void; addHoliday: (holiday: Omit<Holiday, "id">) => void; updateHoliday: (id: string, holiday: Omit<Holiday, "id">) => void; deleteHoliday: (id: string) => void; setWorkingDays: (days: number[]) => void };
type BreakContextValue = { startBreak: (employeeId: string, date: string, time: string) => OperationResult; endBreak: (employeeId: string, date: string, time: string) => OperationResult };
type CorrectionContextValue = { applyAttendanceCorrection: (employeeId: string, date: string, status?: AttendanceStatus, checkIn?: string, checkOut?: string) => OperationResult };
const AttendanceContext = createContext<(ContextValue & BreakContextValue & CorrectionContextValue) | null>(null);
const readArray = <T,>(key: string, fallback: T[], guard: (item: unknown) => item is T) => { try { const value = window.localStorage.getItem(key); if (!value) return fallback; const parsed: unknown = JSON.parse(value); return Array.isArray(parsed) && parsed.every(guard) ? parsed : fallback; } catch { return fallback; } };
const isEmployee = (value: unknown): value is Employee => !!value && typeof value === "object" && typeof (value as Employee).id === "string" && typeof (value as Employee).email === "string";
const isRecord = (value: unknown): value is AttendanceRecord => !!value && typeof value === "object" && typeof (value as AttendanceRecord).employeeId === "string" && /^\d{4}-\d{2}-\d{2}$/.test(String((value as AttendanceRecord).date)) && ["present", "absent", "late", "leave"].includes(String((value as AttendanceRecord).status));
const isLeave = (value: unknown): value is LeaveRequest => !!value && typeof value === "object" && typeof (value as LeaveRequest).id === "string" && ["Pending", "Pending Manager", "Pending HR", "Approved", "Rejected"].includes(String((value as LeaveRequest).status));
const isShift = (value: unknown): value is Shift => !!value && typeof value === "object" && typeof (value as Shift).id === "string" && typeof (value as Shift).name === "string" && /^\d{2}:\d{2}$/.test(String((value as Shift).startTime)) && Array.isArray((value as Shift).workingDays);
const isHoliday = (value: unknown): value is Holiday => !!value && typeof value === "object" && typeof (value as Holiday).id === "string" && /^\d{4}-\d{2}-\d{2}$/.test(String((value as Holiday).date));

export function AttendanceProvider({ children }: { children: React.ReactNode }) {
  const auth = useAuth();
  const [employees, setEmployees] = useState<Employee[]>([]); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>([]); const [balancePolicies, setBalancePolicies] = useState<Record<string, LeaveBalance>>({}); const [allShifts, setAllShifts] = useState<Shift[]>([]); const [assignments, setAssignments] = useState<Record<string, string>>({}); const [holidays, setHolidays] = useState<Holiday[]>([]); const [workingDays, setWorkingDaysState] = useState<number[]>([1, 2, 3, 4, 5]); const [ready, setReady] = useState(false);
  useEffect(() => { queueMicrotask(() => {
    const savedEmployees = readArray(STORAGE_KEYS.employees, seedEmployees, isEmployee); const savedLeaves = readArray(STORAGE_KEYS.leaves, [], isLeave);
    const savedShifts = readArray(STORAGE_KEYS.shifts, seedShifts, isShift); const savedHolidays = readArray(STORAGE_KEYS.holidays, [], isHoliday); const defaults = Object.fromEntries(savedEmployees.map((employee) => [employee.id, "shift-morning"])); let savedAssignments: Record<string, string> = defaults; let savedWorkingDays = [1, 2, 3, 4, 5];
    try { const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.balances) || "{}"); setBalancePolicies(saved && typeof saved === "object" ? saved : {}); const parsedAssignments = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.assignments) || "{}"); savedAssignments = parsedAssignments && typeof parsedAssignments === "object" ? { ...defaults, ...parsedAssignments } : defaults; const parsedDays: unknown = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.workingDays) || "[1,2,3,4,5]"); if (Array.isArray(parsedDays) && parsedDays.every((day) => Number.isInteger(day) && day >= 0 && day <= 6)) savedWorkingDays = [...new Set<number>(parsedDays)]; }
    catch { setBalancePolicies({}); }
    const savedRecords = normalizeAttendanceRecords(readArray(STORAGE_KEYS.attendance, createPracticeRecords(), isRecord)); setEmployees(savedEmployees); setRecords(reconcileClockStatuses(savedRecords, savedAssignments, savedShifts, savedWorkingDays, savedHolidays)); setLeaveRequests(savedLeaves); setAllShifts(savedShifts); setHolidays(savedHolidays); setAssignments(savedAssignments); setWorkingDaysState(savedWorkingDays);
    setReady(true);
  }); }, []);
  const balances = useMemo(() => deriveLeaveBalances(employees.map((employee) => employee.id), balancePolicies, leaveRequests), [employees, balancePolicies, leaveRequests]);
  useEffect(() => { if (!ready) return; try { window.localStorage.setItem(STORAGE_KEYS.employees, JSON.stringify(employees)); window.localStorage.setItem(STORAGE_KEYS.attendance, JSON.stringify(records)); window.localStorage.setItem(STORAGE_KEYS.leaves, JSON.stringify(leaveRequests)); window.localStorage.setItem(STORAGE_KEYS.balances, JSON.stringify(balances)); window.localStorage.setItem(STORAGE_KEYS.shifts, JSON.stringify(allShifts)); window.localStorage.setItem(STORAGE_KEYS.assignments, JSON.stringify(assignments)); window.localStorage.setItem(STORAGE_KEYS.holidays, JSON.stringify(holidays)); window.localStorage.setItem(STORAGE_KEYS.workingDays, JSON.stringify(workingDays)); } catch { /* The application remains usable without persistence. */ } }, [ready, employees, records, leaveRequests, balances, allShifts, assignments, holidays, workingDays]);
  const markAttendance = useCallback((employeeId: string, date: string, status: AttendanceStatus) => { if (!auth.canManageAttendance) return; setRecords((current) => applyManualAttendanceStatus(current, employeeId, date, status)); }, [auth.canManageAttendance]);
  const checkIn = useCallback((employeeId: string, date: string, time: string): OperationResult => {
    if (!auth.currentUser || (!auth.canManageAttendance && auth.currentUser.employeeId !== employeeId)) return { ok: false, message: "You can only check in or out for yourself." };
    const employee = employees.find((item) => item.id === employeeId && !item.deletedAt && item.status === "Active"); if (!employee) return { ok: false, message: "This employee is not active." };
    const existing = records.find((record) => record.employeeId === employeeId && record.date === date); if (existing?.checkIn) return { ok: false, message: `Already checked in at ${existing.checkIn}.` }; if (existing?.source === "approved-leave") return { ok: false, message: "Approved leave is recorded for this date." };
    const shiftId = assignments[employeeId]; const shift = allShifts.find((item) => item.id === shiftId && !item.deletedAt && item.status === "Active"); if (!shift) return { ok: false, message: "Assign an active shift before checking in." }; let instance: ScheduleInstance | undefined; try { const parsed: unknown = JSON.parse(window.localStorage.getItem(WORKFORCE_KEYS.schedules) || "[]"); if (Array.isArray(parsed)) instance = parsed.find((item): item is ScheduleInstance => !!item && typeof item === "object" && (item as ScheduleInstance).employeeId === employeeId && (item as ScheduleInstance).date === date && /^\d{2}:\d{2}$/.test(String((item as ScheduleInstance).startTime)) && /^\d{2}:\d{2}$/.test(String((item as ScheduleInstance).endTime))); } catch { /* Fall back to the assigned template. */ } const instanceShift = instance && allShifts.find((item) => item.id === instance.shiftId && !item.deletedAt && item.status === "Active"); const clockShift = instance ? { ...(instanceShift || shift), id: instance.shiftId, startTime: instance.startTime, endTime: instance.endTime } : shift; if (!isScheduledDate(date, workingDays, holidays, clockShift)) return { ok: false, message: "Check-in is unavailable on a holiday or non-working day." }; const automaticStatus: AttendanceStatus = isLateCheckIn(time, clockShift) ? "late" : "present";
    setRecords((current) => { const currentRecord = current.find((record) => record.employeeId === employeeId && record.date === date); const next: AttendanceRecord = currentRecord ? { ...currentRecord, checkIn: time, shiftId: currentRecord.shiftId || clockShift.id, scheduledStart: currentRecord.scheduledStart || clockShift.startTime, scheduledEnd: currentRecord.scheduledEnd || clockShift.endTime, statusSource: currentRecord.statusSource || "manual" } : { employeeId, date, status: automaticStatus, source: "check-in", statusSource: "automatic", checkIn: time, shiftId: clockShift.id, scheduledStart: clockShift.startTime, scheduledEnd: clockShift.endTime }; return [...current.filter((record) => !(record.employeeId === employeeId && record.date === date)), next]; });
    return { ok: true, message: `Checked in at ${time} as ${existing ? existing.status : automaticStatus}.` };
  }, [auth, employees, records, assignments, allShifts, workingDays, holidays]);
  const checkOut = useCallback((employeeId: string, date: string, time: string): OperationResult => { if (!auth.currentUser || (!auth.canManageAttendance && auth.currentUser.employeeId !== employeeId)) return { ok: false, message: "You can only check in or out for yourself." }; const existing = records.find((record) => record.employeeId === employeeId && record.date === date); if (!existing?.checkIn) return { ok: false, message: "Check in before checking out." }; if (existing.checkOut) return { ok: false, message: `Already checked out at ${existing.checkOut}.` }; if (timeToMinutes(time) <= timeToMinutes(existing.checkIn)) return { ok: false, message: "Check-out time must be after check-in time." }; const shift = allShifts.find((item) => item.id === (existing.shiftId || assignments[employeeId])); if (!shift) return { ok: false, message: "The assigned shift could not be found." }; const clockShift = existing.scheduledStart && existing.scheduledEnd ? { ...shift, startTime: existing.scheduledStart, endTime: existing.scheduledEnd } : shift; if ((existing.breaks || []).some((item) => !item.end)) return { ok: false, message: "End the active break before checking out." }; const metrics = calculateTimeMetrics(existing.checkIn, time, clockShift, breakMinutesFor(existing)); setRecords((current) => current.map((record) => record.employeeId === employeeId && record.date === date ? { ...record, checkOut: time, ...metrics } : record)); return { ok: true, message: `Checked out at ${time}. Worked ${Math.floor(metrics.workedMinutes / 60)}h ${metrics.workedMinutes % 60}m.` }; }, [auth, records, allShifts, assignments]);
  const startBreak = useCallback((employeeId: string, date: string, time: string): OperationResult => { if (!auth.currentUser || (!auth.canManageAttendance && auth.currentUser.employeeId !== employeeId)) return { ok: false, message: "You can only manage breaks for yourself." }; const existing = records.find((item) => item.employeeId === employeeId && item.date === date); if (!existing?.checkIn) return { ok: false, message: "Check in before starting a break." }; if (existing.checkOut) return { ok: false, message: "The workday is already complete." }; if ((existing.breaks || []).some((item) => !item.end)) return { ok: false, message: "A break is already active." }; setRecords((items) => items.map((item) => item.employeeId === employeeId && item.date === date ? { ...item, breaks: [...(item.breaks || []), { id: crypto.randomUUID(), start: time }] } : item)); return { ok: true, message: `Break started at ${time}.` }; }, [auth, records]);
  const endBreak = useCallback((employeeId: string, date: string, time: string): OperationResult => { if (!auth.currentUser || (!auth.canManageAttendance && auth.currentUser.employeeId !== employeeId)) return { ok: false, message: "You can only manage breaks for yourself." }; const existing = records.find((item) => item.employeeId === employeeId && item.date === date); const activeBreak = existing?.breaks?.find((item) => !item.end); if (!activeBreak) return { ok: false, message: "There is no active break." }; if (timeToMinutes(time) <= timeToMinutes(activeBreak.start)) return { ok: false, message: "Break end must be after break start." }; setRecords((items) => items.map((item) => item.employeeId === employeeId && item.date === date ? { ...item, breaks: (item.breaks || []).map((entry) => entry.id === activeBreak.id ? { ...entry, end: time } : entry) } : item)); return { ok: true, message: `Break ended at ${time}.` }; }, [auth, records]);
  const applyAttendanceCorrection = useCallback((employeeId: string, date: string, status?: AttendanceStatus, correctedIn?: string, correctedOut?: string): OperationResult => { const allowed = !!auth.currentUser && (auth.canManageAttendance || (auth.role === "manager" && auth.currentUser.teamIds.includes(employeeId))); if (!allowed) return { ok: false, message: "You cannot correct this attendance record." }; const existing = records.find((item) => item.employeeId === employeeId && item.date === date); if (existing?.source === "approved-leave") return { ok: false, message: "Approved-leave attendance cannot be overwritten by a correction." }; const checkIn = correctedIn || existing?.checkIn; const checkOut = correctedOut || existing?.checkOut; if (checkOut && !checkIn) return { ok: false, message: "A checkout requires a check-in." }; if (checkIn && checkOut && timeToMinutes(checkOut) <= timeToMinutes(checkIn)) return { ok: false, message: "Check-out time must be after check-in time." }; const shift = allShifts.find((item) => item.id === (existing?.shiftId || assignments[employeeId])); const clockShift = shift && existing?.scheduledStart && existing.scheduledEnd ? { ...shift, startTime: existing.scheduledStart, endTime: existing.scheduledEnd } : shift; const metrics = checkIn && checkOut && clockShift ? calculateTimeMetrics(checkIn, checkOut, clockShift, breakMinutesFor(existing)) : {}; const next: AttendanceRecord = { ...(existing || { employeeId, date, source: "manual" as const }), status: status || existing?.status || "present", statusSource: "manual", checkIn, checkOut, ...metrics }; setRecords((items) => [...items.filter((item) => !(item.employeeId === employeeId && item.date === date)), next]); return { ok: true, message: "Attendance correction applied." }; }, [auth, records, allShifts, assignments]);
  const reconcileRecords = useCallback((nextAssignments = assignments, nextShifts = allShifts, nextWorkingDays = workingDays, nextHolidays = holidays) => setRecords((current) => reconcileClockStatuses(current, nextAssignments, nextShifts, nextWorkingDays, nextHolidays)), [assignments, allShifts, workingDays, holidays]);
  const addEmployee = useCallback((employee: EmployeeInput) => { if (!auth.canManageEmployees) return; setEmployees((current) => [...current, employee]); setBalancePolicies((current) => ({ ...current, [employee.id]: defaultBalance() })); setAssignments((current) => ({ ...current, [employee.id]: allShifts.find((shift) => shift.status === "Active" && !shift.deletedAt)?.id || "" })); }, [auth.canManageEmployees, allShifts]);
  const updateEmployee = useCallback((originalId: string, employee: EmployeeInput) => { if (!auth.canManageEmployees) return; setEmployees((current) => current.map((item) => item.id === originalId ? employee : item)); if (originalId !== employee.id) { setRecords((current) => current.map((record) => record.employeeId === originalId ? { ...record, employeeId: employee.id } : record)); setLeaveRequests((current) => current.map((request) => request.employeeId === originalId ? { ...request, employeeId: employee.id } : request)); setBalancePolicies((current) => { const next = { ...current, [employee.id]: current[originalId] || defaultBalance() }; delete next[originalId]; return next; }); setAssignments((current) => { const next = { ...current, [employee.id]: current[originalId] || "" }; delete next[originalId]; return next; }); } }, [auth.canManageEmployees]);
  const deleteEmployee = useCallback((id: string) => { if (auth.canDeleteEmployees) setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, deletedAt: new Date().toISOString() } : employee)); }, [auth.canDeleteEmployees]);
  const setEmployeeActive = useCallback((id: string, active: boolean) => { if (auth.canManageEmployees) setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, status: active ? "Active" : "Inactive" } : employee)); }, [auth.canManageEmployees]);
  const setEmployeeShift = useCallback((employeeId: string, shiftId: string) => { if (!auth.canManageShifts) return; const next = { ...assignments, [employeeId]: shiftId }; setAssignments(next); reconcileRecords(next); }, [auth.canManageShifts, assignments, reconcileRecords]);
  const addLeaveRequest = useCallback((request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => { if (!auth.currentUser || (auth.currentUser.role === "employee" && auth.currentUser.employeeId !== request.employeeId) || (auth.currentUser.role === "manager" && !auth.currentUser.teamIds.includes(request.employeeId))) return; setLeaveRequests((current) => [...current, { ...request, id: crypto.randomUUID(), requestDate: getToday(), status: "Pending Manager" }]); }, [auth.currentUser]);
  const updateLeaveStatus = useCallback((id: string, status: LeaveStatus) => { const request = leaveRequests.find((item) => item.id === id); if (!request || request.status === status || !auth.currentUser || auth.role === "employee" || auth.currentUser.employeeId === request.employeeId) return; const managerAllowed = auth.role === "manager" && auth.currentUser.teamIds.includes(request.employeeId) && ["Pending", "Pending Manager"].includes(request.status) && ["Pending HR", "Approved", "Rejected"].includes(status); const hrAllowed = (auth.role === "admin" || auth.role === "hr") && ["Pending", "Pending Manager", "Pending HR"].includes(request.status) && ["Approved", "Rejected"].includes(status); if (!managerAllowed && !hrAllowed) return; setLeaveRequests((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setRecords((attendance) => { const withoutGenerated = attendance.filter((record) => record.leaveRequestId !== id); if (status !== "Approved") return withoutGenerated; const occupied = new Set(withoutGenerated.filter((record) => record.employeeId === request.employeeId).map((record) => record.date)); const generated = datesInclusive(request.startDate, request.endDate).filter((date) => !occupied.has(date)).map((date): AttendanceRecord => ({ employeeId: request.employeeId, date, status: "leave", source: "approved-leave", statusSource: "approved-leave", leaveRequestId: id })); return [...withoutGenerated, ...generated]; }); }, [leaveRequests, auth]);
  const addShift = useCallback((shift: Omit<Shift, "id">) => { if (!auth.canManageShifts) return; setAllShifts((current) => [...current, { ...shift, id: crypto.randomUUID() }]); }, [auth.canManageShifts]); const updateShift = useCallback((id: string, shift: Omit<Shift, "id">) => { if (!auth.canManageShifts) return; const next = allShifts.map((item) => item.id === id ? { ...shift, id } : item); setAllShifts(next); reconcileRecords(assignments, next); }, [auth.canManageShifts, allShifts, assignments, reconcileRecords]); const deleteShift = useCallback((id: string) => { if (!auth.canManageShifts) return; setAllShifts((current) => current.map((item) => item.id === id ? { ...item, status: "Inactive", deletedAt: new Date().toISOString() } : item)); }, [auth.canManageShifts]); const setShiftActive = useCallback((id: string, active: boolean) => { if (!auth.canManageShifts) return; setAllShifts((current) => current.map((item) => item.id === id ? { ...item, status: active ? "Active" : "Inactive" } : item)); }, [auth.canManageShifts]);
  const addHoliday = useCallback((holiday: Omit<Holiday, "id">) => { if (!auth.canManageHolidays) return; setHolidays((current) => [...current, { ...holiday, id: crypto.randomUUID() }]); }, [auth.canManageHolidays]); const updateHoliday = useCallback((id: string, holiday: Omit<Holiday, "id">) => { if (!auth.canManageHolidays) return; const next = holidays.map((item) => item.id === id ? { ...holiday, id } : item); setHolidays(next); reconcileRecords(assignments, allShifts, workingDays, next); }, [auth.canManageHolidays, holidays, assignments, allShifts, workingDays, reconcileRecords]); const deleteHoliday = useCallback((id: string) => { if (!auth.canManageHolidays) return; const next = holidays.filter((item) => item.id !== id); setHolidays(next); reconcileRecords(assignments, allShifts, workingDays, next); }, [auth.canManageHolidays, holidays, assignments, allShifts, workingDays, reconcileRecords]);
  const setWorkingDays = useCallback((days: number[]) => { setWorkingDaysState(days); reconcileRecords(assignments, allShifts, days, holidays); }, [assignments, allShifts, holidays, reconcileRecords]);
  const authorizedEmployees = useMemo(() => auth.currentUser ? getVisibleEmployees(employees, auth.currentUser) : [], [employees, auth.currentUser]); const visibleEmployees = useMemo(() => authorizedEmployees.filter((employee) => !employee.deletedAt), [authorizedEmployees]); const activeEmployees = useMemo(() => visibleEmployees.filter((employee) => employee.status === "Active"), [visibleEmployees]); const visibleRecords = useMemo(() => auth.currentUser ? getVisibleAttendance(records, auth.currentUser) : [], [records, auth.currentUser]); const visibleLeaves = useMemo(() => auth.currentUser ? getVisibleLeaveRequests(leaveRequests, auth.currentUser) : [], [leaveRequests, auth.currentUser]);
  const shifts = useMemo(() => allShifts.filter((shift) => !shift.deletedAt), [allShifts]);
  const value = useMemo(() => ({ employees: visibleEmployees, allEmployees: authorizedEmployees, activeEmployees, records: visibleRecords, leaveRequests: visibleLeaves, balances, shifts, allShifts, assignments, holidays, workingDays, ready, markAttendance, checkIn, checkOut, startBreak, endBreak, applyAttendanceCorrection, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, setEmployeeShift, addLeaveRequest, updateLeaveStatus, addShift, updateShift, deleteShift, setShiftActive, addHoliday, updateHoliday, deleteHoliday, setWorkingDays }), [visibleEmployees, authorizedEmployees, activeEmployees, visibleRecords, visibleLeaves, balances, shifts, allShifts, assignments, holidays, workingDays, ready, markAttendance, checkIn, checkOut, startBreak, endBreak, applyAttendanceCorrection, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, setEmployeeShift, addLeaveRequest, updateLeaveStatus, addShift, updateShift, deleteShift, setShiftActive, addHoliday, updateHoliday, deleteHoliday, setWorkingDays]);
  return <AttendanceContext.Provider value={value}>{children}</AttendanceContext.Provider>;
}
export function useAttendance() { const context = useContext(AttendanceContext); if (!context) throw new Error("useAttendance must be used within AttendanceProvider"); return context; }
