"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Employee, employees as seedEmployees } from "@/data/employees";
import { AttendanceRecord, AttendanceStatus, applyManualAttendanceStatus, createPracticeRecords, getToday, normalizeAttendanceRecords } from "@/lib/attendance";
import { LeaveBalance, LeaveRequest, LeaveStatus, datesInclusive, defaultBalance, deriveLeaveBalances } from "@/lib/leave";
import { Holiday, Shift, calculateTimeMetrics, isLateCheckIn, isScheduledDate, reconcileClockStatuses, timeToMinutes } from "@/lib/scheduling";
import { seedShifts } from "@/data/schedules";

export const STORAGE_KEYS = { employees: "northstar-employees-v1", attendance: "northstar-attendance-records-v1", leaves: "northstar-leave-requests-v1", balances: "northstar-leave-balances-v1", shifts: "northstar-shifts-v1", assignments: "northstar-employee-shifts-v1", holidays: "northstar-holidays-v1", workingDays: "northstar-working-days-v1" } as const;
type EmployeeInput = Omit<Employee, "deletedAt">;
type OperationResult = { ok: boolean; message: string };
type ContextValue = { employees: Employee[]; allEmployees: Employee[]; activeEmployees: Employee[]; records: AttendanceRecord[]; leaveRequests: LeaveRequest[]; balances: Record<string, LeaveBalance>; shifts: Shift[]; allShifts: Shift[]; assignments: Record<string, string>; holidays: Holiday[]; workingDays: number[]; ready: boolean; markAttendance: (employeeId: string, date: string, status: AttendanceStatus) => void; checkIn: (employeeId: string, date: string, time: string) => OperationResult; checkOut: (employeeId: string, date: string, time: string) => OperationResult; addEmployee: (employee: EmployeeInput) => void; updateEmployee: (originalId: string, employee: EmployeeInput) => void; deleteEmployee: (id: string) => void; setEmployeeActive: (id: string, active: boolean) => void; setEmployeeShift: (employeeId: string, shiftId: string) => void; addLeaveRequest: (request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => void; updateLeaveStatus: (id: string, status: LeaveStatus) => void; addShift: (shift: Omit<Shift, "id">) => void; updateShift: (id: string, shift: Omit<Shift, "id">) => void; deleteShift: (id: string) => void; setShiftActive: (id: string, active: boolean) => void; addHoliday: (holiday: Omit<Holiday, "id">) => void; updateHoliday: (id: string, holiday: Omit<Holiday, "id">) => void; deleteHoliday: (id: string) => void; setWorkingDays: (days: number[]) => void };
const AttendanceContext = createContext<ContextValue | null>(null);
const readArray = <T,>(key: string, fallback: T[], guard: (item: unknown) => item is T) => { try { const value = window.localStorage.getItem(key); if (!value) return fallback; const parsed: unknown = JSON.parse(value); return Array.isArray(parsed) && parsed.every(guard) ? parsed : fallback; } catch { return fallback; } };
const isEmployee = (value: unknown): value is Employee => !!value && typeof value === "object" && typeof (value as Employee).id === "string" && typeof (value as Employee).email === "string";
const isRecord = (value: unknown): value is AttendanceRecord => !!value && typeof value === "object" && typeof (value as AttendanceRecord).employeeId === "string" && /^\d{4}-\d{2}-\d{2}$/.test(String((value as AttendanceRecord).date)) && ["present", "absent", "late", "leave"].includes(String((value as AttendanceRecord).status));
const isLeave = (value: unknown): value is LeaveRequest => !!value && typeof value === "object" && typeof (value as LeaveRequest).id === "string" && ["Pending", "Approved", "Rejected"].includes(String((value as LeaveRequest).status));
const isShift = (value: unknown): value is Shift => !!value && typeof value === "object" && typeof (value as Shift).id === "string" && typeof (value as Shift).name === "string" && /^\d{2}:\d{2}$/.test(String((value as Shift).startTime)) && Array.isArray((value as Shift).workingDays);
const isHoliday = (value: unknown): value is Holiday => !!value && typeof value === "object" && typeof (value as Holiday).id === "string" && /^\d{4}-\d{2}-\d{2}$/.test(String((value as Holiday).date));

export function AttendanceProvider({ children }: { children: React.ReactNode }) {
  const [employees, setEmployees] = useState<Employee[]>([]); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>([]); const [balancePolicies, setBalancePolicies] = useState<Record<string, LeaveBalance>>({}); const [allShifts, setAllShifts] = useState<Shift[]>([]); const [assignments, setAssignments] = useState<Record<string, string>>({}); const [holidays, setHolidays] = useState<Holiday[]>([]); const [workingDays, setWorkingDaysState] = useState<number[]>([1, 2, 3, 4, 5]); const [ready, setReady] = useState(false);
  useEffect(() => { queueMicrotask(() => {
    const savedEmployees = readArray(STORAGE_KEYS.employees, seedEmployees, isEmployee); const savedLeaves = readArray(STORAGE_KEYS.leaves, [], isLeave);
    const savedShifts = readArray(STORAGE_KEYS.shifts, seedShifts, isShift); const savedHolidays = readArray(STORAGE_KEYS.holidays, [], isHoliday); const defaults = Object.fromEntries(savedEmployees.map((employee) => [employee.id, "shift-morning"])); let savedAssignments: Record<string, string> = defaults; let savedWorkingDays = [1, 2, 3, 4, 5];
    try { const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.balances) || "{}"); setBalancePolicies(saved && typeof saved === "object" ? saved : {}); const parsedAssignments = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.assignments) || "{}"); savedAssignments = parsedAssignments && typeof parsedAssignments === "object" ? { ...defaults, ...parsedAssignments } : defaults; const parsedDays: unknown = JSON.parse(window.localStorage.getItem(STORAGE_KEYS.workingDays) || "[1,2,3,4,5]"); if (Array.isArray(parsedDays) && parsedDays.every((day) => Number.isInteger(day) && day >= 0 && day <= 6)) savedWorkingDays = [...new Set<number>(parsedDays)]; }
    catch { setBalancePolicies({}); }
    const savedRecords = normalizeAttendanceRecords(readArray(STORAGE_KEYS.attendance, createPracticeRecords(), isRecord)); setEmployees(savedEmployees); setRecords(reconcileClockStatuses(savedRecords, savedAssignments, savedShifts, savedWorkingDays, savedHolidays)); setLeaveRequests(savedLeaves); setAllShifts(savedShifts); setHolidays(savedHolidays); setAssignments(savedAssignments); setWorkingDaysState(savedWorkingDays);
    setReady(true);
  }); }, []);
  const balances = useMemo(() => deriveLeaveBalances(employees.map((employee) => employee.id), balancePolicies, leaveRequests), [employees, balancePolicies, leaveRequests]);
  useEffect(() => { if (!ready) return; try { window.localStorage.setItem(STORAGE_KEYS.employees, JSON.stringify(employees)); window.localStorage.setItem(STORAGE_KEYS.attendance, JSON.stringify(records)); window.localStorage.setItem(STORAGE_KEYS.leaves, JSON.stringify(leaveRequests)); window.localStorage.setItem(STORAGE_KEYS.balances, JSON.stringify(balances)); window.localStorage.setItem(STORAGE_KEYS.shifts, JSON.stringify(allShifts)); window.localStorage.setItem(STORAGE_KEYS.assignments, JSON.stringify(assignments)); window.localStorage.setItem(STORAGE_KEYS.holidays, JSON.stringify(holidays)); window.localStorage.setItem(STORAGE_KEYS.workingDays, JSON.stringify(workingDays)); } catch { /* The application remains usable without persistence. */ } }, [ready, employees, records, leaveRequests, balances, allShifts, assignments, holidays, workingDays]);
  const markAttendance = useCallback((employeeId: string, date: string, status: AttendanceStatus) => setRecords((current) => applyManualAttendanceStatus(current, employeeId, date, status)), []);
  const checkIn = useCallback((employeeId: string, date: string, time: string): OperationResult => {
    const employee = employees.find((item) => item.id === employeeId && !item.deletedAt && item.status === "Active"); if (!employee) return { ok: false, message: "This employee is not active." };
    const existing = records.find((record) => record.employeeId === employeeId && record.date === date); if (existing?.checkIn) return { ok: false, message: `Already checked in at ${existing.checkIn}.` }; if (existing?.source === "approved-leave") return { ok: false, message: "Approved leave is recorded for this date." };
    const shiftId = assignments[employeeId]; const shift = allShifts.find((item) => item.id === shiftId && !item.deletedAt && item.status === "Active"); if (!shift) return { ok: false, message: "Assign an active shift before checking in." }; const automaticStatus: AttendanceStatus = isScheduledDate(date, workingDays, holidays, shift) && isLateCheckIn(time, shift) ? "late" : "present";
    setRecords((current) => { const currentRecord = current.find((record) => record.employeeId === employeeId && record.date === date); const next: AttendanceRecord = currentRecord ? { ...currentRecord, checkIn: time, shiftId: currentRecord.shiftId || shift.id, statusSource: currentRecord.statusSource || "manual" } : { employeeId, date, status: automaticStatus, source: "check-in", statusSource: "automatic", checkIn: time, shiftId: shift.id }; return [...current.filter((record) => !(record.employeeId === employeeId && record.date === date)), next]; });
    return { ok: true, message: `Checked in at ${time} as ${existing ? existing.status : automaticStatus}.` };
  }, [employees, records, assignments, allShifts, workingDays, holidays]);
  const checkOut = useCallback((employeeId: string, date: string, time: string): OperationResult => { const existing = records.find((record) => record.employeeId === employeeId && record.date === date); if (!existing?.checkIn) return { ok: false, message: "Check in before checking out." }; if (existing.checkOut) return { ok: false, message: `Already checked out at ${existing.checkOut}.` }; if (timeToMinutes(time) <= timeToMinutes(existing.checkIn)) return { ok: false, message: "Check-out time must be after check-in time." }; const shift = allShifts.find((item) => item.id === (existing.shiftId || assignments[employeeId])); if (!shift) return { ok: false, message: "The assigned shift could not be found." }; const metrics = calculateTimeMetrics(existing.checkIn, time, shift); setRecords((current) => current.map((record) => record.employeeId === employeeId && record.date === date ? { ...record, checkOut: time, ...metrics } : record)); return { ok: true, message: `Checked out at ${time}. Worked ${Math.floor(metrics.workedMinutes / 60)}h ${metrics.workedMinutes % 60}m.` }; }, [records, allShifts, assignments]);
  const reconcileRecords = useCallback((nextAssignments = assignments, nextShifts = allShifts, nextWorkingDays = workingDays, nextHolidays = holidays) => setRecords((current) => reconcileClockStatuses(current, nextAssignments, nextShifts, nextWorkingDays, nextHolidays)), [assignments, allShifts, workingDays, holidays]);
  const addEmployee = useCallback((employee: EmployeeInput) => { setEmployees((current) => [...current, employee]); setBalancePolicies((current) => ({ ...current, [employee.id]: defaultBalance() })); setAssignments((current) => ({ ...current, [employee.id]: allShifts.find((shift) => shift.status === "Active" && !shift.deletedAt)?.id || "" })); }, [allShifts]);
  const updateEmployee = useCallback((originalId: string, employee: EmployeeInput) => { setEmployees((current) => current.map((item) => item.id === originalId ? employee : item)); if (originalId !== employee.id) { setRecords((current) => current.map((record) => record.employeeId === originalId ? { ...record, employeeId: employee.id } : record)); setLeaveRequests((current) => current.map((request) => request.employeeId === originalId ? { ...request, employeeId: employee.id } : request)); setBalancePolicies((current) => { const next = { ...current, [employee.id]: current[originalId] || defaultBalance() }; delete next[originalId]; return next; }); setAssignments((current) => { const next = { ...current, [employee.id]: current[originalId] || "" }; delete next[originalId]; return next; }); } }, []);
  const deleteEmployee = useCallback((id: string) => setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, deletedAt: new Date().toISOString() } : employee)), []);
  const setEmployeeActive = useCallback((id: string, active: boolean) => setEmployees((current) => current.map((employee) => employee.id === id ? { ...employee, status: active ? "Active" : "Inactive" } : employee)), []);
  const setEmployeeShift = useCallback((employeeId: string, shiftId: string) => { const next = { ...assignments, [employeeId]: shiftId }; setAssignments(next); reconcileRecords(next); }, [assignments, reconcileRecords]);
  const addLeaveRequest = useCallback((request: Omit<LeaveRequest, "id" | "requestDate" | "status">) => setLeaveRequests((current) => [...current, { ...request, id: crypto.randomUUID(), requestDate: getToday(), status: "Pending" }]), []);
  const updateLeaveStatus = useCallback((id: string, status: LeaveStatus) => { const request = leaveRequests.find((item) => item.id === id); if (!request || request.status === status) return; setLeaveRequests((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setRecords((attendance) => { const withoutGenerated = attendance.filter((record) => record.leaveRequestId !== id); if (status !== "Approved") return withoutGenerated; const occupied = new Set(withoutGenerated.filter((record) => record.employeeId === request.employeeId).map((record) => record.date)); const generated = datesInclusive(request.startDate, request.endDate).filter((date) => !occupied.has(date)).map((date): AttendanceRecord => ({ employeeId: request.employeeId, date, status: "leave", source: "approved-leave", statusSource: "approved-leave", leaveRequestId: id })); return [...withoutGenerated, ...generated]; }); }, [leaveRequests]);
  const addShift = useCallback((shift: Omit<Shift, "id">) => setAllShifts((current) => [...current, { ...shift, id: crypto.randomUUID() }]), []); const updateShift = useCallback((id: string, shift: Omit<Shift, "id">) => { const next = allShifts.map((item) => item.id === id ? { ...shift, id } : item); setAllShifts(next); reconcileRecords(assignments, next); }, [allShifts, assignments, reconcileRecords]); const deleteShift = useCallback((id: string) => setAllShifts((current) => current.map((item) => item.id === id ? { ...item, status: "Inactive", deletedAt: new Date().toISOString() } : item)), []); const setShiftActive = useCallback((id: string, active: boolean) => setAllShifts((current) => current.map((item) => item.id === id ? { ...item, status: active ? "Active" : "Inactive" } : item)), []);
  const addHoliday = useCallback((holiday: Omit<Holiday, "id">) => setHolidays((current) => [...current, { ...holiday, id: crypto.randomUUID() }]), []); const updateHoliday = useCallback((id: string, holiday: Omit<Holiday, "id">) => { const next = holidays.map((item) => item.id === id ? { ...holiday, id } : item); setHolidays(next); reconcileRecords(assignments, allShifts, workingDays, next); }, [holidays, assignments, allShifts, workingDays, reconcileRecords]); const deleteHoliday = useCallback((id: string) => { const next = holidays.filter((item) => item.id !== id); setHolidays(next); reconcileRecords(assignments, allShifts, workingDays, next); }, [holidays, assignments, allShifts, workingDays, reconcileRecords]);
  const setWorkingDays = useCallback((days: number[]) => { setWorkingDaysState(days); reconcileRecords(assignments, allShifts, days, holidays); }, [assignments, allShifts, holidays, reconcileRecords]);
  const visibleEmployees = useMemo(() => employees.filter((employee) => !employee.deletedAt), [employees]); const activeEmployees = useMemo(() => visibleEmployees.filter((employee) => employee.status === "Active"), [visibleEmployees]);
  const shifts = useMemo(() => allShifts.filter((shift) => !shift.deletedAt), [allShifts]);
  const value = useMemo(() => ({ employees: visibleEmployees, allEmployees: employees, activeEmployees, records, leaveRequests, balances, shifts, allShifts, assignments, holidays, workingDays, ready, markAttendance, checkIn, checkOut, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, setEmployeeShift, addLeaveRequest, updateLeaveStatus, addShift, updateShift, deleteShift, setShiftActive, addHoliday, updateHoliday, deleteHoliday, setWorkingDays }), [visibleEmployees, employees, activeEmployees, records, leaveRequests, balances, shifts, allShifts, assignments, holidays, workingDays, ready, markAttendance, checkIn, checkOut, addEmployee, updateEmployee, deleteEmployee, setEmployeeActive, setEmployeeShift, addLeaveRequest, updateLeaveStatus, addShift, updateShift, deleteShift, setShiftActive, addHoliday, updateHoliday, deleteHoliday, setWorkingDays]);
  return <AttendanceContext.Provider value={value}>{children}</AttendanceContext.Provider>;
}
export function useAttendance() { const context = useContext(AttendanceContext); if (!context) throw new Error("useAttendance must be used within AttendanceProvider"); return context; }
