"use client";
import { FormEvent, ReactNode, useState } from "react";
import { useRouter } from "next/navigation";
import { useAttendance } from "@/components/attendance-provider";
import { Employee, EmployeeStatus, employeeStatuses } from "@/data/employees";
import { getToday } from "@/lib/attendance";
import { shiftArrangement, shiftDisplayName } from "@/lib/scheduling";
type FormValues = Omit<Employee, "deletedAt">;
const blank: FormValues = { id: "", name: "", email: "", phone: "", department: "", role: "", status: "Active", joiningDate: getToday(), initials: "", manager: "", location: "" };
export function EmployeeForm({ employee }: { employee?: Employee }) {
  const router = useRouter(); const { employees, shifts, assignments, addEmployee, updateEmployee, setEmployeeShift } = useAttendance(); const [values, setValues] = useState<FormValues>(employee || blank); const [shiftId, setShiftId] = useState(employee ? assignments[employee.id] || "" : ""); const [errors, setErrors] = useState<Record<string, string>>({});
  const set = (field: keyof FormValues, value: string) => setValues((current) => ({ ...current, [field]: value }));
  function submit(event: FormEvent) { event.preventDefault(); const nextErrors: Record<string, string> = {}; const required: (keyof FormValues)[] = ["id", "name", "email", "phone", "department", "role", "joiningDate", "manager", "location"]; required.forEach((field) => { if (!String(values[field]).trim()) nextErrors[field] = "This field is required."; }); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) nextErrors.email = "Enter a valid email address."; const idTaken = employees.some((item) => item.id.toLowerCase() === values.id.trim().toLowerCase() && item.id !== employee?.id); const emailTaken = employees.some((item) => item.email.toLowerCase() === values.email.trim().toLowerCase() && item.id !== employee?.id); if (idTaken) nextErrors.id = "This employee ID is already in use."; if (emailTaken) nextErrors.email = "This email is already in use."; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; const normalized = { ...values, id: values.id.trim().toUpperCase(), name: values.name.trim(), email: values.email.trim().toLowerCase(), initials: values.initials.trim().toUpperCase() || values.name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() }; if (employee) { updateEmployee(employee.id, normalized); setEmployeeShift(employee.id, shiftId); } else addEmployee(normalized); router.push(employee ? `/employees/${encodeURIComponent(normalized.id)}` : "/employees"); }
  const field = (name: keyof FormValues, label: string, type = "text", placeholder = "") => <label className="form-field"><span>{label}{name !== "initials" && <> <b aria-hidden="true">*</b></>}</span><input type={type} value={String(values[name])} placeholder={placeholder} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `${name}-error` : undefined} onChange={(event) => set(name, event.target.value)} />{errors[name] && <small id={`${name}-error`} role="alert">{errors[name]}</small>}</label>;
  const section = (title: string, description: string, children: ReactNode) => <section className="employee-form-section"><div className="employee-form-heading"><h2>{title}</h2><p>{description}</p></div><div className="grid gap-5 sm:grid-cols-2">{children}</div></section>;
  const selectedShift = shifts.find((item) => item.id === shiftId);
  return <form onSubmit={submit} noValidate className="panel overflow-hidden">
    <div className="px-5 py-4 sm:px-6"><p className="text-sm text-slate-500">Fields marked with <b className="text-rose-500">*</b> are required.</p></div>
    {section("Personal information", "Identity and contact details.", <>{field("name", "Full name", "text", "e.g. Ali Hassan")}{employee ? <label className="form-field"><span>Employee ID</span><input value={values.id} disabled aria-describedby="employee-id-help" /><small className="!text-slate-500" id="employee-id-help">Fixed to preserve linked records.</small></label> : field("id", "Employee ID", "text", "e.g. EMP-1011")}{field("email", "Email", "email", "name@northstar.co")}{field("phone", "Phone", "tel", "+92 300 000 0000")}{field("initials", "Profile initials (optional)")}</>)}
    {section("Employment information", "Role, reporting line and start date.", <>{field("joiningDate", "Joining date", "date")}{field("manager", "Manager")}{field("department", "Department")}{field("role", "Role / job title")}</>)}
    {section("Shift & work arrangement", "Location and assigned working pattern.", <>{field("location", "Work location")}{employee ? <label className="form-field"><span>Assigned shift</span><select value={shiftId} onChange={(event) => setShiftId(event.target.value)}><option value="">Unassigned</option>{shifts.filter((item) => item.status === "Active" || item.id === shiftId).map((item) => <option key={item.id} value={item.id}>{shiftDisplayName(item)} · {shiftArrangement(item)} ({item.startTime}–{item.endTime})</option>)}</select></label> : <div className="form-note">Shift assignment is available after the employee record is created.</div>}{selectedShift && <div className="form-note sm:col-span-2"><b>{shiftArrangement(selectedShift)}</b> work arrangement · {selectedShift.startTime}–{selectedShift.endTime}</div>}</>)}
    {section("Status", "Employment record availability.", <><label className="form-field"><span>Employment status</span><select value={values.status} onChange={(event) => set("status", event.target.value as EmployeeStatus)}>{employeeStatuses.map((status) => <option key={status}>{status}</option>)}</select></label></>)}
    <div className="flex flex-col-reverse gap-3 border-t border-slate-100 bg-slate-50/60 p-5 sm:flex-row sm:justify-end sm:px-6"><button type="button" className="btn-secondary" onClick={() => router.back()}>Cancel</button><button className="btn-primary" type="submit">{employee ? "Save changes" : "Add employee"}</button></div>
  </form>;
}
