"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useAttendance } from "@/components/attendance-provider";
import { Employee, EmployeeStatus } from "@/data/employees";
import { getToday } from "@/lib/attendance";
type FormValues = Omit<Employee, "deletedAt">;
const blank: FormValues = { id: "", name: "", email: "", phone: "", department: "", role: "", status: "Active", joiningDate: getToday(), initials: "", manager: "", location: "" };
export function EmployeeForm({ employee }: { employee?: Employee }) {
  const router = useRouter(); const { employees, addEmployee, updateEmployee } = useAttendance(); const [values, setValues] = useState<FormValues>(employee || blank); const [errors, setErrors] = useState<Record<string, string>>({});
  const set = (field: keyof FormValues, value: string) => setValues((current) => ({ ...current, [field]: value }));
  function submit(event: FormEvent) { event.preventDefault(); const nextErrors: Record<string, string> = {}; const required: (keyof FormValues)[] = ["id", "name", "email", "phone", "department", "role", "joiningDate", "manager", "location"]; required.forEach((field) => { if (!String(values[field]).trim()) nextErrors[field] = "This field is required."; }); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) nextErrors.email = "Enter a valid email address."; const idTaken = employees.some((item) => item.id.toLowerCase() === values.id.trim().toLowerCase() && item.id !== employee?.id); const emailTaken = employees.some((item) => item.email.toLowerCase() === values.email.trim().toLowerCase() && item.id !== employee?.id); if (idTaken) nextErrors.id = "This employee ID is already in use."; if (emailTaken) nextErrors.email = "This email is already in use."; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; const normalized = { ...values, id: values.id.trim().toUpperCase(), name: values.name.trim(), email: values.email.trim().toLowerCase(), initials: values.initials.trim().toUpperCase() || values.name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase() }; if (employee) updateEmployee(employee.id, normalized); else addEmployee(normalized); router.push(employee ? `/employees/${encodeURIComponent(normalized.id)}` : "/employees"); }
  const field = (name: keyof FormValues, label: string, type = "text", placeholder = "") => <label className="form-field"><span>{label} <b aria-hidden="true">*</b></span><input type={type} value={String(values[name])} placeholder={placeholder} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `${name}-error` : undefined} onChange={(event) => set(name, event.target.value)} />{errors[name] && <small id={`${name}-error`} role="alert">{errors[name]}</small>}</label>;
  return <form onSubmit={submit} noValidate className="panel"><div className="panel-heading"><div><h2 className="section-title">Employee information</h2><p className="section-copy">Fields marked with * are required</p></div></div><div className="grid gap-5 p-5 sm:grid-cols-2">{field("name", "Full name", "text", "e.g. Ali Hassan")}{field("id", "Employee ID", "text", "e.g. EMP-1011")}{field("email", "Email", "email", "name@northstar.co")}{field("phone", "Phone", "tel", "+92 300 000 0000")}{field("department", "Department")}{field("role", "Role / job title")}{field("joiningDate", "Joining date", "date")}{field("manager", "Manager")}{field("location", "Work location")}<label className="form-field"><span>Employment status</span><select value={values.status} onChange={(event) => set("status", event.target.value as EmployeeStatus)}><option>Active</option><option>Inactive</option></select></label>{field("initials", "Profile initials (optional)")}</div><div className="flex flex-col-reverse gap-3 border-t border-slate-100 p-5 sm:flex-row sm:justify-end"><button type="button" className="btn-secondary" onClick={() => router.back()}>Cancel</button><button className="btn-primary" type="submit">{employee ? "Save changes" : "Add employee"}</button></div></form>;
}
