"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react"; import { useAuth } from "@/components/auth-provider"; import { useAttendance } from "@/components/attendance-provider"; import { getToday } from "@/lib/attendance"; import { AuditEntry, CorrectionRequest, Department, defaultSettings, OPERATIONS_KEYS, OrganizationSettings } from "@/lib/operations"; import { defaultDepartments } from "@/data/employees";
type Notification = { id: string; title: string; detail: string; href: string };
type Value = { corrections: CorrectionRequest[]; audits: AuditEntry[]; departments: Department[]; settings: OrganizationSettings; notifications: Notification[]; unreadCount: number; submitCorrection: (input: Pick<CorrectionRequest, "employeeId" | "attendanceDate" | "requestedStatus" | "requestedCheckIn" | "requestedCheckOut" | "reason">) => void; reviewCorrection: (id: string, status: "Approved" | "Rejected", note: string) => void; addDepartment: (input: Omit<Department, "id">) => void; updateDepartment: (id: string, input: Omit<Department, "id">) => void; updateSettings: (next: OrganizationSettings) => void; markRead: (id: string) => void; markAllRead: () => void; addAudit: (action: string, entityType: string, entityId: string, description: string, before?: string, after?: string) => void };
const Context = createContext<Value | null>(null);
const read = <T,>(key: string, fallback: T): T => { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };
export function OperationsProvider({ children }: { children: React.ReactNode }) { const auth = useAuth(); const attendance = useAttendance(); const [corrections, setCorrections] = useState<CorrectionRequest[]>([]); const [audits, setAudits] = useState<AuditEntry[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [settings, setSettings] = useState(defaultSettings); const [reads, setReads] = useState<string[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { queueMicrotask(() => { setCorrections(read(OPERATIONS_KEYS.corrections, [])); setAudits(read(OPERATIONS_KEYS.audit, [])); setDepartments(read(OPERATIONS_KEYS.departments, defaultDepartments.map((name) => ({ id: `dept-${name.toLowerCase().replaceAll(" ", "-")}`, name, managerEmployeeId: "", status: "Active" as const })))); setSettings(read(OPERATIONS_KEYS.settings, defaultSettings)); setReads(read(OPERATIONS_KEYS.notificationReads, [])); setReady(true); }); }, []);
  useEffect(() => { if (!ready) return; localStorage.setItem(OPERATIONS_KEYS.corrections, JSON.stringify(corrections)); localStorage.setItem(OPERATIONS_KEYS.audit, JSON.stringify(audits)); localStorage.setItem(OPERATIONS_KEYS.departments, JSON.stringify(departments)); localStorage.setItem(OPERATIONS_KEYS.settings, JSON.stringify(settings)); localStorage.setItem(OPERATIONS_KEYS.notificationReads, JSON.stringify(reads)); }, [ready, corrections, audits, departments, settings, reads]);
  const addAudit = useCallback((action: string, entityType: string, entityId: string, description: string, before?: string, after?: string) => { if (!auth.currentUser) return; setAudits((items) => [{ id: crypto.randomUUID(), timestamp: new Date().toISOString(), actorId: auth.currentUser!.id, actorName: auth.currentUser!.name, role: auth.currentUser!.role, action, entityType, entityId, description, before, after }, ...items]); }, [auth.currentUser]);
  const visibleIds = useMemo(() => new Set(attendance.allEmployees.map((item) => item.id)), [attendance.allEmployees]); const visibleCorrections = useMemo(() => corrections.filter((item) => visibleIds.has(item.employeeId)), [corrections, visibleIds]);
  const submitCorrection = useCallback((input: Pick<CorrectionRequest, "employeeId" | "attendanceDate" | "requestedStatus" | "requestedCheckIn" | "requestedCheckOut" | "reason">) => { if (!auth.currentUser || (auth.currentUser.role === "employee" && auth.currentUser.employeeId !== input.employeeId) || !visibleIds.has(input.employeeId)) return; const item: CorrectionRequest = { ...input, id: crypto.randomUUID(), requestDate: getToday(), status: "Pending" }; setCorrections((items) => [item, ...items]); addAudit("submitted", "attendance correction", item.id, `Correction requested for ${input.employeeId} on ${input.attendanceDate}.`); }, [auth.currentUser, visibleIds, addAudit]);
  const reviewCorrection = useCallback((id: string, status: "Approved" | "Rejected", note: string) => { const item = corrections.find((entry) => entry.id === id); if (!item || !auth.currentUser || auth.currentUser.role === "employee" || !visibleIds.has(item.employeeId)) return; if (status === "Approved" && item.requestedStatus) attendance.markAttendance(item.employeeId, item.attendanceDate, item.requestedStatus); setCorrections((items) => items.map((entry) => entry.id === id ? { ...entry, status, reviewedBy: auth.currentUser!.name, reviewNote: note } : entry)); addAudit(status.toLowerCase(), "attendance correction", id, `${status} correction for ${item.employeeId} on ${item.attendanceDate}.`); }, [corrections, auth.currentUser, visibleIds, attendance, addAudit]);
  const addDepartment = useCallback((input: Omit<Department, "id">) => { if (!auth.canManageEmployees) return; const item = { ...input, id: crypto.randomUUID() }; setDepartments((items) => [...items, item]); addAudit("created", "department", item.id, `Created ${item.name}.`); }, [auth.canManageEmployees, addAudit]); const updateDepartment = useCallback((id: string, input: Omit<Department, "id">) => { if (!auth.canManageEmployees) return; setDepartments((items) => items.map((item) => item.id === id ? { ...input, id } : item)); addAudit("updated", "department", id, `Updated ${input.name}.`); }, [auth.canManageEmployees, addAudit]); const updateSettings = useCallback((next: OrganizationSettings) => { if (auth.role !== "admin") return; const before = JSON.stringify(settings); setSettings(next); attendance.setWorkingDays(next.workingDays); addAudit("updated", "organization settings", "organization", "Updated organization attendance settings.", before, JSON.stringify(next)); }, [auth.role, settings, attendance, addAudit]);
  const notifications = useMemo<Notification[]>(() => { const today = getToday(); const items: Notification[] = []; const pendingLeaves = attendance.leaveRequests.filter((item) => item.status.startsWith("Pending")); if (pendingLeaves.length) items.push({ id: `leaves-${pendingLeaves.length}`, title: `${pendingLeaves.length} pending leave request${pendingLeaves.length === 1 ? "" : "s"}`, detail: "Review requests in your authorized scope.", href: "/leave" }); if (visibleCorrections.filter((item) => item.status === "Pending").length) items.push({ id: `corrections-${visibleCorrections.filter((item) => item.status === "Pending").length}`, title: `${visibleCorrections.filter((item) => item.status === "Pending").length} pending correction request(s)`, detail: "Attendance corrections await review.", href: "/corrections" }); const missing = attendance.records.filter((item) => item.date === today && item.checkIn && !item.checkOut).length; if (missing) items.push({ id: `missing-${today}-${missing}`, title: `${missing} missing checkout${missing === 1 ? "" : "s"}`, detail: "Employees are currently checked in.", href: "/attendance" }); const holiday = [...attendance.holidays].filter((item) => item.date >= today).sort((a, b) => a.date.localeCompare(b.date))[0]; if (holiday) items.push({ id: `holiday-${holiday.id}`, title: `Upcoming: ${holiday.name}`, detail: holiday.date, href: auth.role === "admin" || auth.role === "hr" ? "/holidays" : "/schedule" }); return items; }, [attendance.leaveRequests, attendance.records, attendance.holidays, visibleCorrections, auth.role]);
  const value = useMemo<Value>(() => ({ corrections: visibleCorrections, audits, departments, settings, notifications, unreadCount: notifications.filter((item) => !reads.includes(item.id)).length, submitCorrection, reviewCorrection, addDepartment, updateDepartment, updateSettings, markRead: (id) => setReads((items) => items.includes(id) ? items : [...items, id]), markAllRead: () => setReads((items) => [...new Set([...items, ...notifications.map((item) => item.id)])]), addAudit }), [visibleCorrections, audits, departments, settings, notifications, reads, submitCorrection, reviewCorrection, addDepartment, updateDepartment, updateSettings, addAudit]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useOperations() { const value = useContext(Context); if (!value) throw new Error("useOperations must be used within OperationsProvider"); return value; }
