import { AttendanceStatus, attendanceStatusLabels } from "@/lib/attendance";
import { Icon, IconName } from "@/components/icons";
export function Avatar({ initials }: { initials: string }) { return <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-blue-700 ring-1 ring-slate-200">{initials}</span>; }
export function StatusBadge({ status }: { status: AttendanceStatus }) { return <span className={`status-badge status-${status}`}>{attendanceStatusLabels[status]}</span>; }
export function EmployeeStatusBadge({ status }: { status: string }) { return <span className={`status-badge ${status === "Active" ? "status-present" : status === "Terminated" ? "status-terminated" : "status-inactive"}`}>{status}</span>; }
export function ProgressBar({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-label={`${value}% attendance`} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-blue-600 transition-[width]" style={{ width: `${value}%` }} /></div>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-1 text-xs font-semibold uppercase tracking-[.14em] text-blue-600">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500 sm:text-base">{description}</p></div>{action}</header>; }
export function StatCard({ label, value, tone, icon }: { label: string; value: string | number; tone: string; icon: IconName }) { return <article className="stat-card panel flex items-center gap-5 px-5 py-4"><div className={`stat-icon stat-${tone}`}><Icon name={icon} /></div><div><p className="text-sm font-medium text-slate-700">{label}</p><p className={`mt-1 text-3xl font-bold stat-value-${tone}`}>{value}</p></div></article>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="empty-state"><div className="empty-icon"><Icon name="search" /></div><h3>{title}</h3><p>{description}</p></div>; }
