"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { useAttendance } from "@/components/attendance-provider";
import { useOperations } from "@/components/operations-provider";
import { ScheduleInstance, TimesheetApproval, TimesheetStatus, WORKFORCE_KEYS, scheduleKey } from "@/lib/workforce";

type Result = { ok: boolean; message: string };
type ScheduleInput = Pick<ScheduleInstance, "employeeId" | "date" | "shiftId" | "startTime" | "endTime">;
type Value = { schedules: ScheduleInstance[]; approvals: TimesheetApproval[]; saveSchedule: (input: ScheduleInput) => Result; removeSchedule: (id: string) => Result; reviewTimesheet: (employeeId: string, date: string, status: Exclude<TimesheetStatus, "Pending">, note: string) => Result };
const Context = createContext<Value | null>(null);
const read = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } };

export function WorkforceProvider({ children }: { children: React.ReactNode }) {
  const auth = useAuth(); const attendance = useAttendance(); const operations = useOperations();
  const [allSchedules, setSchedules] = useState<ScheduleInstance[]>([]); const [allApprovals, setApprovals] = useState<TimesheetApproval[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { queueMicrotask(() => { setSchedules(read(WORKFORCE_KEYS.schedules, [])); setApprovals(read(WORKFORCE_KEYS.timesheets, [])); setReady(true); }); }, []);
  useEffect(() => { if (!ready) return; localStorage.setItem(WORKFORCE_KEYS.schedules, JSON.stringify(allSchedules)); localStorage.setItem(WORKFORCE_KEYS.timesheets, JSON.stringify(allApprovals)); }, [ready, allSchedules, allApprovals]);
  const visibleIds = useMemo(() => new Set(attendance.employees.map((item) => item.id).filter((id) => auth.role !== "manager" || auth.currentUser?.teamIds.includes(id))), [attendance.employees, auth.role, auth.currentUser]);
  const canManage = useCallback((employeeId: string) => !!auth.currentUser && auth.role !== "employee" && (auth.role !== "manager" || auth.currentUser.teamIds.includes(employeeId)) && visibleIds.has(employeeId), [auth.currentUser, auth.role, visibleIds]);
  const saveSchedule = useCallback((input: ScheduleInput): Result => { if (!canManage(input.employeeId)) return { ok: false, message: "You cannot manage this employee's schedule." }; const employee = attendance.allEmployees.find((item) => item.id === input.employeeId); if (!employee || employee.status !== "Active") return { ok: false, message: "Inactive employees cannot be scheduled." }; if (attendance.holidays.some((item) => item.date === input.date)) return { ok: false, message: "Conflict: this date is a holiday." }; if (attendance.leaveRequests.some((item) => item.employeeId === input.employeeId && item.status === "Approved" && item.startDate <= input.date && item.endDate >= input.date)) return { ok: false, message: "Conflict: approved leave overlaps this schedule." }; if (input.endTime <= input.startTime) return { ok: false, message: "End time must be after start time." }; const existing = allSchedules.find((item) => scheduleKey(item.employeeId, item.date) === scheduleKey(input.employeeId, input.date)); const now = new Date().toISOString(); const next: ScheduleInstance = { ...input, id: existing?.id || crypto.randomUUID(), status: existing ? "Changed" : "Scheduled", createdAt: existing?.createdAt || now, updatedAt: now }; setSchedules((items) => [...items.filter((item) => item.id !== next.id), next]); operations.addAudit(existing ? "changed" : "created", "schedule", next.id, `${existing ? "Changed" : "Created"} schedule for ${input.employeeId} on ${input.date}.`, existing ? JSON.stringify(existing) : undefined, JSON.stringify(next)); return { ok: true, message: existing ? "Schedule updated." : "Schedule created." }; }, [canManage, attendance.allEmployees, attendance.holidays, attendance.leaveRequests, allSchedules, operations]);
  const removeSchedule = useCallback((id: string): Result => { const item = allSchedules.find((entry) => entry.id === id); if (!item || !canManage(item.employeeId)) return { ok: false, message: "Schedule not found or not authorized." }; if (item.date < new Date().toISOString().slice(0, 10)) return { ok: false, message: "Historical schedules cannot be removed." }; setSchedules((items) => items.filter((entry) => entry.id !== id)); operations.addAudit("removed", "schedule", id, `Removed schedule for ${item.employeeId} on ${item.date}.`, JSON.stringify(item)); return { ok: true, message: "Future schedule removed." }; }, [allSchedules, canManage, operations]);
  const reviewTimesheet = useCallback((employeeId: string, date: string, status: Exclude<TimesheetStatus, "Pending">, note: string): Result => { if (!canManage(employeeId) || auth.currentUser?.employeeId === employeeId) return { ok: false, message: "You cannot review this timesheet." }; const decision = { id: crypto.randomUUID(), employeeId, date, status, note, reviewedBy: auth.currentUser!.name, reviewedAt: new Date().toISOString() }; setApprovals((items) => { const old = items.find((item) => item.employeeId === employeeId && item.date === date); return [...items.filter((item) => !(item.employeeId === employeeId && item.date === date)), { employeeId, date, status, note, reviewedBy: decision.reviewedBy, reviewedAt: decision.reviewedAt, history: [...(old?.history || []), decision] }]; }); operations.addAudit(status.toLowerCase(), "timesheet", scheduleKey(employeeId, date), `${status} timesheet for ${employeeId} on ${date}.`); return { ok: true, message: `Timesheet ${status.toLowerCase()}.` }; }, [canManage, auth.currentUser, operations]);
  const value = useMemo(() => ({ schedules: allSchedules.filter((item) => visibleIds.has(item.employeeId)), approvals: allApprovals.filter((item) => visibleIds.has(item.employeeId)), saveSchedule, removeSchedule, reviewTimesheet }), [allSchedules, allApprovals, visibleIds, saveSchedule, removeSchedule, reviewTimesheet]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useWorkforce() { const value = useContext(Context); if (!value) throw new Error("useWorkforce must be used within WorkforceProvider"); return value; }
