"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { Icon, IconName } from "@/components/icons";
import { useOperations } from "@/components/operations-provider";
import { PageHeading } from "@/components/ui";
import { weekDays } from "@/lib/scheduling";

export default function SettingsPage() {
  const { role } = useAuth(); const { settings, updateSettings, audits } = useOperations(); const [values, setValues] = useState(settings); const readOnly = role !== "admin"; function submit(event: FormEvent) { event.preventDefault(); updateSettings(values); }
  const areas: Array<{ title: string; description: string; href: string; icon: IconName; tone: string }> = [
    { title: "Organization", description: "Manage company profile, departments, locations, and teams.", href: "/departments", icon: "dashboard", tone: "blue" },
    { title: "Roles & permissions", description: "Review role-based access and administrative activity.", href: "/audit", icon: "people", tone: "violet" },
    { title: "Working days & shifts", description: "Configure working days, holidays, and shift schedules.", href: "/shifts", icon: "calendar", tone: "green" },
    { title: "Attendance rules", description: "Set grace periods, attendance rules, and overtime policy.", href: "#organization-policy", icon: "clock", tone: "amber" },
    { title: "Leave policies", description: "Review leave types, balances, and approval workflows.", href: "/leave", icon: "calendar", tone: "blue" },
    { title: "Security", description: "Review access controls and the immutable activity history.", href: "/audit", icon: "records", tone: "red" },
  ];
  return <div className="admin-reference space-y-6"><PageHeading title="Administration" description="Manage organization policy, workforce configuration, and system controls." />
    <section className="admin-launch-grid">{areas.map((area) => <Link className="admin-launch-card" href={area.href} key={area.title}><span className={`stat-icon stat-${area.tone}`}><Icon name={area.icon} /></span><h2>{area.title}</h2><p>{area.description}</p><span aria-hidden="true">→</span></Link>)}</section>
    <section className="grid gap-5 xl:grid-cols-[.78fr_1.22fr]"><article className="reference-security-card"><div className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-orange-500 text-white"><Icon name="records" /></span><div><h2 className="text-lg font-bold text-slate-950">Security checks</h2><p className="text-sm text-slate-500">Review current organization security essentials.</p></div></div><div className="mt-8 grid grid-cols-3 divide-x divide-orange-200"><div><b>{role === "admin" ? 1 : 0}</b><span>Active admin session</span></div><div><b>{audits.length}</b><span>Recorded audit events</span></div><div><b>{settings.defaultGraceMinutes}<small> min</small></b><span>Attendance grace period</span></div></div><Link className="btn-secondary mt-8 border-orange-300 text-orange-600" href="/audit">Review security</Link></article><article className="panel overflow-hidden"><div className="reference-card-heading"><h2>Recent admin activity</h2><Link className="btn-secondary !min-h-9 text-xs" href="/audit">View audit log</Link></div><div className="table-wrap"><table className="min-w-[600px]"><thead><tr><th>Actor</th><th>Action</th><th>Target</th><th>Time</th></tr></thead><tbody>{audits.slice(0, 5).map((item) => <tr key={item.id}><td className="font-semibold text-slate-900">{item.actorName}</td><td className="capitalize">{item.action}<small className="block text-slate-400">{item.entityType}</small></td><td>{item.entityId}</td><td>{new Date(item.timestamp).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</td></tr>)}</tbody></table></div></article></section>
    <form className="panel overflow-hidden" id="organization-policy" onSubmit={submit}><div className="panel-heading"><div><h2 className="section-title">Organization & attendance policy</h2><p className="section-copy">{readOnly ? "HR has read-only access to organization policy." : "Configure the settings used by existing attendance and leave workflows."}</p></div></div><fieldset disabled={readOnly}><div className="grid gap-5 p-5 sm:grid-cols-2"><label className="form-field"><span>Organization name</span><input value={values.organizationName} onChange={(event) => setValues({ ...values, organizationName: event.target.value })} /></label><label className="form-field"><span>Timezone</span><input value={values.timezone} onChange={(event) => setValues({ ...values, timezone: event.target.value })} /></label><label className="form-field"><span>Default grace period</span><input type="number" min="0" value={values.defaultGraceMinutes} onChange={(event) => setValues({ ...values, defaultGraceMinutes: Number(event.target.value) })} /></label><label className="form-field"><span>Overtime policy</span><input value={values.overtimePolicy} onChange={(event) => setValues({ ...values, overtimePolicy: event.target.value })} /></label><label className="form-field"><span>Attendance percentage rule</span><input value={values.attendancePercentageRule} onChange={(event) => setValues({ ...values, attendancePercentageRule: event.target.value })} /></label><label className="form-field"><span>Leave approval mode</span><select value={values.leaveApprovalMode} onChange={(event) => setValues({ ...values, leaveApprovalMode: event.target.value as typeof values.leaveApprovalMode })}><option value="manager-and-hr">Manager and HR</option><option value="hr-only">HR only</option></select></label><fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Default working days</legend><div className="mt-2 flex flex-wrap gap-2">{weekDays.map((day) => <button type="button" className={`day-toggle ${values.workingDays.includes(day.value) ? "selected" : ""}`} key={day.value} onClick={() => setValues({ ...values, workingDays: values.workingDays.includes(day.value) ? values.workingDays.filter((item) => item !== day.value) : [...values.workingDays, day.value] })}>{day.short}</button>)}</div></fieldset><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={values.managerApprovalRequired} onChange={(event) => setValues({ ...values, managerApprovalRequired: event.target.checked })} /> Manager approval required</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={values.hrFinalApprovalRequired} onChange={(event) => setValues({ ...values, hrFinalApprovalRequired: event.target.checked })} /> HR final approval required</label></div></fieldset>{!readOnly && <div className="flex justify-end border-t border-slate-100 bg-slate-50/60 p-5"><button className="btn-primary">Save settings</button></div>}</form></div>;
}
