"use client";
import { FormEvent, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { useOperations } from "@/components/operations-provider";
import { PageHeading } from "@/components/ui";
import { weekDays } from "@/lib/scheduling";

export default function SettingsPage() {
  const { role } = useAuth(); const { settings, updateSettings } = useOperations(); const [values, setValues] = useState(settings); const readOnly = role !== "admin"; function submit(event: FormEvent) { event.preventDefault(); updateSettings(values); }
  return <div className="space-y-6"><PageHeading title="Organization settings" description={readOnly ? "HR has read-only access to organization policy." : "Configure attendance, working-day, and approval policies."} /><form className="panel overflow-hidden" onSubmit={submit}><fieldset disabled={readOnly}><div className="grid gap-5 p-5 sm:grid-cols-2"><label className="form-field"><span>Organization name</span><input value={values.organizationName} onChange={(event) => setValues({ ...values, organizationName: event.target.value })} /></label><label className="form-field"><span>Timezone</span><input value={values.timezone} onChange={(event) => setValues({ ...values, timezone: event.target.value })} /></label><label className="form-field"><span>Default grace period</span><input type="number" min="0" value={values.defaultGraceMinutes} onChange={(event) => setValues({ ...values, defaultGraceMinutes: Number(event.target.value) })} /></label><label className="form-field"><span>Overtime policy</span><input value={values.overtimePolicy} onChange={(event) => setValues({ ...values, overtimePolicy: event.target.value })} /></label><label className="form-field"><span>Attendance percentage rule</span><input value={values.attendancePercentageRule} onChange={(event) => setValues({ ...values, attendancePercentageRule: event.target.value })} /></label><label className="form-field"><span>Leave approval mode</span><select value={values.leaveApprovalMode} onChange={(event) => setValues({ ...values, leaveApprovalMode: event.target.value as typeof values.leaveApprovalMode })}><option value="manager-and-hr">Manager and HR</option><option value="hr-only">HR only</option></select></label><fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Default working days</legend><div className="mt-2 flex flex-wrap gap-2">{weekDays.map((day) => <button type="button" className={`day-toggle ${values.workingDays.includes(day.value) ? "selected" : ""}`} key={day.value} onClick={() => setValues({ ...values, workingDays: values.workingDays.includes(day.value) ? values.workingDays.filter((item) => item !== day.value) : [...values.workingDays, day.value] })}>{day.short}</button>)}</div></fieldset><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={values.managerApprovalRequired} onChange={(event) => setValues({ ...values, managerApprovalRequired: event.target.checked })} /> Manager approval required</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={values.hrFinalApprovalRequired} onChange={(event) => setValues({ ...values, hrFinalApprovalRequired: event.target.checked })} /> HR final approval required</label></div></fieldset>{!readOnly && <div className="flex justify-end border-t border-slate-100 bg-slate-50/60 p-5"><button className="btn-primary">Save settings</button></div>}</form></div>;
}
