"use client";
import Link from "next/link"; import { useMemo, useState } from "react";
import { useAttendance } from "@/components/attendance-provider"; import { Avatar, EmployeeStatusBadge, EmptyState, PageHeading } from "@/components/ui"; import { Icon } from "@/components/icons";
export default function EmployeesPage() {
  const { employees, setEmployeeActive, deleteEmployee } = useAttendance(); const [search, setSearch] = useState(""); const [department, setDepartment] = useState(""); const [status, setStatus] = useState(""); const departments = [...new Set(employees.map((employee) => employee.department))].sort();
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return employees.filter((employee) => (!query || [employee.name, employee.email, employee.id].some((value) => value.toLowerCase().includes(query))) && (!department || employee.department === department) && (!status || employee.status === status)); }, [employees, search, department, status]);
  const remove = (id: string, name: string) => { if (window.confirm(`Delete ${name}? Their historical records will be retained.`)) deleteEmployee(id); };
  return <div className="space-y-6"><PageHeading title="Employees" description="Add, update, and manage everyone in your organization." action={<Link className="btn-primary" href="/employees/new">Add employee</Link>} />
    <div className="filter-bar"><label className="search-field"><span className="sr-only">Search employees by name, ID, or email</span><Icon name="search" className="h-4 w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, ID or email" /></label><label className="filter-field"><span>Department</span><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label><label className="filter-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>Active</option><option>Inactive</option></select></label></div>
    <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">Employee directory</h2><p className="section-copy">{filtered.length} of {employees.length} employees</p></div></div>{filtered.length === 0 ? <EmptyState title={employees.length ? "No employees found" : "No employees yet"} description={employees.length ? "Try adjusting your search or filters." : "Add your first employee to get started."} /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((employee) => <tr key={employee.id}><td><Link href={`/employees/${encodeURIComponent(employee.id)}`} className="flex items-center gap-3 hover:text-blue-600"><Avatar initials={employee.initials} /><div><p className="font-semibold text-slate-900">{employee.name}</p><p className="text-xs text-slate-500">{employee.id} · {employee.email}</p></div></Link></td><td>{employee.department}</td><td>{employee.role}</td><td><EmployeeStatusBadge status={employee.status} /></td><td><div className="flex gap-2"><Link className="table-action" href={`/employees/${encodeURIComponent(employee.id)}/edit`}>Edit</Link><button className="table-action" onClick={() => setEmployeeActive(employee.id, employee.status !== "Active")}>{employee.status === "Active" ? "Deactivate" : "Activate"}</button><button className="table-action text-rose-600" onClick={() => remove(employee.id, employee.name)}>Delete</button></div></td></tr>)}</tbody></table></div>}</div></div>;
}
