"use client";
import { useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { Avatar, PageHeading, StatusBadge } from "@/components/ui";
import { attendanceStatuses, formatLongDate, getToday } from "@/lib/attendance";
export default function AttendancePage() {
  const [date, setDate] = useState(getToday); const { records, markAttendance, activeEmployees: employees } = useAttendance(); const selected = records.filter((record) => record.date === date); const marked = selected.filter((record) => employees.some((employee) => employee.id === record.employeeId)).length; const progress = employees.length ? Math.round(marked / employees.length * 100) : 0;
  return <div className="space-y-6"><PageHeading title="Mark attendance" description="Set or update one attendance status per active employee and date." action={<label className="date-field"><span>Date</span><input type="date" value={date} max={getToday()} onChange={(event) => setDate(event.target.value)} /></label>} />
    <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">{formatLongDate(date)}</h2><p className="section-copy">{marked} of {employees.length} employees marked</p></div><div className="hidden sm:flex items-center gap-2"><div className="h-2 w-24 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${progress}%` }} /></div><span className="text-xs font-semibold text-slate-500">{progress}%</span></div></div>
      <div className="divide-y divide-slate-100">{employees.map((employee) => { const current = selected.find((record) => record.employeeId === employee.id)?.status; return <div key={employee.id} className="p-4 sm:flex sm:items-center sm:gap-5"><div className="flex min-w-0 flex-1 items-center gap-3"><Avatar initials={employee.initials} /><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{employee.name}</p><p className="truncate text-xs text-slate-500">{employee.department} · {employee.role}</p></div>{current && <span className="ml-auto sm:hidden"><StatusBadge status={current} /></span>}</div><div className="mt-3 grid grid-cols-2 gap-2 sm:mt-0 sm:flex" role="group" aria-label={`Attendance status for ${employee.name}`}>{attendanceStatuses.map((status) => <button key={status} onClick={() => markAttendance(employee.id, date, status)} aria-pressed={current === status} className={`attendance-button attendance-${status} ${current === status ? "selected" : ""}`}>{status[0].toUpperCase() + status.slice(1)}</button>)}</div></div>; })}</div>
    </div></div>;
}
