"use client";
import { useState } from "react"; import { useAttendance } from "@/components/attendance-provider"; import { Avatar, EmptyState, PageHeading, StatusBadge } from "@/components/ui"; import { attendanceStatuses, formatLongDate, getToday } from "@/lib/attendance"; import { isScheduledDate } from "@/lib/scheduling";
const currentTime = () => new Date().toTimeString().slice(0, 5);
export default function AttendancePage() {
  const [date, setDate] = useState(getToday); const [notice, setNotice] = useState<{ ok: boolean; message: string }>(); const { records, markAttendance, checkIn, checkOut, activeEmployees: employees, shifts, assignments, holidays, workingDays } = useAttendance(); const selected = records.filter((record) => record.date === date); const marked = selected.filter((record) => employees.some((employee) => employee.id === record.employeeId)).length; const progress = employees.length ? Math.round(marked / employees.length * 100) : 0; const holiday = holidays.find((item) => item.date === date); const organizationScheduled = isScheduledDate(date, workingDays, holidays); const allowClock = date === getToday();
  const clock = (kind: "in" | "out", employeeId: string) => setNotice(kind === "in" ? checkIn(employeeId, date, currentTime()) : checkOut(employeeId, date, currentTime()));
  return <div className="space-y-6"><PageHeading title="Mark attendance" description="Set manual status or use live check-in and check-out for active employees." action={<label className="date-field"><span>Date</span><input type="date" value={date} max={getToday()} onChange={(event) => { setDate(event.target.value); setNotice(undefined); }} /></label>} />
    {(holiday || !organizationScheduled) && <div className="schedule-banner"><b>{holiday ? holiday.name : "Weekend / non-working day"}</b><span>{holiday ? `${holiday.type}. Normal attendance is not expected.` : "This date is outside the configured organization working days."}</span></div>}{notice && <div role="status" className={`notice ${notice.ok ? "notice-success" : "notice-error"}`}>{notice.message}</div>}
    <div className="panel overflow-hidden"><div className="panel-heading"><div><h2 className="section-title">{formatLongDate(date)}</h2><p className="section-copy">{marked} of {employees.length} active employees marked</p></div><div className="hidden items-center gap-2 sm:flex"><div className="h-2 w-24 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{ width: `${progress}%` }} /></div><span className="text-xs font-semibold text-slate-500">{progress}%</span></div></div>
      {employees.length === 0 ? <EmptyState title="No active employees" description="Activate or add an employee to mark attendance." /> : <div className="divide-y divide-slate-100">{employees.map((employee) => { const current = selected.find((record) => record.employeeId === employee.id); const shift = shifts.find((item) => item.id === assignments[employee.id]); const scheduled = isScheduledDate(date, workingDays, holidays, shift); const leaveLocked = current?.source === "approved-leave"; return <div key={employee.id} className="p-4"><div className="flex min-w-0 items-center gap-3"><Avatar initials={employee.initials} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{employee.name}</p><p className="truncate text-xs text-slate-500">{shift?.name || "No shift assigned"} · {scheduled ? `${shift?.startTime || "--"}–${shift?.endTime || "--"}` : "Not scheduled"}</p></div>{current && <StatusBadge status={current.status} />}</div><div className="mt-3 flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div className="grid grid-cols-2 gap-2 sm:flex" role="group" aria-label={`Attendance status for ${employee.name}`}>{attendanceStatuses.map((status) => <button key={status} disabled={leaveLocked} onClick={() => markAttendance(employee.id, date, status)} aria-pressed={current?.status === status} className={`attendance-button attendance-${status} ${current?.status === status ? "selected" : ""}`}>{status[0].toUpperCase() + status.slice(1)}</button>)}</div><div className="flex flex-wrap items-center gap-2"><span className="text-xs text-slate-500">In: <b>{current?.checkIn || "--:--"}</b> · Out: <b>{current?.checkOut || "--:--"}</b></span><button className="btn-secondary min-h-9 px-3 py-1.5 text-xs" disabled={!allowClock || !!current?.checkIn || leaveLocked || !shift} onClick={() => clock("in", employee.id)}>Check in</button><button className="btn-secondary min-h-9 px-3 py-1.5 text-xs" disabled={!allowClock || !current?.checkIn || !!current.checkOut} onClick={() => clock("out", employee.id)}>Check out</button></div></div>{leaveLocked && <p className="mt-2 text-xs font-medium text-blue-600">Approved leave · manual status is locked</p>}</div>; })}</div>}
    </div></div>;
}
